return {
  { prefix = "beg",   desc = "begin{} / end{}",                  body = { "\\begin{$1}", "\t$0", "\\end{$1}" } },
  { prefix = "ali",   desc = "aligned numbered equation",        body = { "\\begin{align}", "\t$1", "\\end{align}", "$0" } },
  { prefix = "gat",   desc = "gather",                           body = { "\\begin{gather}", "\t$1", "\\end{gather}", "$0" } },
  { prefix = "ngat",  desc = "gather without numbering",         body = { "\\begin{gather*}", "\t$1", "\\end{gather*}", "$0" } },
  { prefix = "nali",  desc = "aligned unnumbered equation",      body = { "\\begin{align*}", "\t$1", "\\end{align*}", "$0" } },
  { prefix = "itm",   desc = "begin itemize",                    body = { "\\begin{itemize}", "\t\\item $0", "\\end{itemize}" } },
  { prefix = "itm-",  desc = "begin itemize with arrow bullet",  body = { "\\begin{itemize}", "\t\\item[\\(\\to\\)] $1", "\\end{itemize}", "$0" } },
  { prefix = "otm",   desc = "item with bullet option",          body = "\\item[${1:}] $0" },
  { prefix = "enu",   desc = "begin enumerate",                  body = { "\\begin{enumerate}", "\t\\item $1", "\\end{enumerate}", "$0" } },
  { prefix = "im",    desc = "inline mathzone",                  body = "\\($1\\)$0" },
  { prefix = "mm",    desc = "math",                             body = { "\\[", "\t$1", "\\] $0" } },
  { prefix = "^",     desc = "superscript",                      body = "^{$1}$0" },
  { prefix = "int",   desc = "integral",                         body = "\\int_{${1:}}^{${2:\\infty}} $3 \\dd $0" },
  { prefix = "dint",  desc = "infinite integral",                body = "\\int_{${1:-\\infty}}^{${2:\\infty}} $3 $4 \\dd $0" },
  { prefix = "lim",   desc = "limit",                            body = "\\lim_{${1:n} \\to ${2:\\infty}} " },
  { prefix = "sum",   desc = "summation",                        body = "\\sum_{${1:n=1}}^{${2:\\infty}} ${3:a_n z^n}" },
  { prefix = "sm",    desc = "short summation",                  body = "\\sum_{${1:n>0}}$0" },
  { prefix = "prod",  desc = "product",                          body = "\\prod_{${1:n}=${2:1}}^{${3:\\infty}} $4 $0" },
  { prefix = "prd",   desc = "short product",                    body = "\\prod_{${1:}}$0" },
  { prefix = "od",    desc = "ordinary derivative",              body = "\\frac{\\dd $1}{\\dd $2}$0" },
  { prefix = "sod",   desc = "second order ordinary derivative", body = "\\frac{\\dd^2 $1}{\\dd $2^2}$0" },
  { prefix = "pd",    desc = "partial derivative",               body = "\\frac{\\partial $1}{\\partial $2}$0" },
  { prefix = "spd",   desc = "second order partial derivative",  body = "\\frac{\\partial^2 $1}{\\partial $2^2}$0" },
  { prefix = "ubr",   desc = "underbrace",                       body = "\\underbrace{$1}$0" },
  { prefix = "sqr",   desc = "squareroot",                       body = "\\sqrt{$1} $0" },
  { prefix = "tx",    desc = "text in math environment",         body = "\\text{$1}$0" },
  { prefix = "frac",  desc = "fraction",                         body = "\\frac{$1}{$2}$0" },
  { prefix = "num",   desc = "fraction with numerator",          body = "\\frac{$1}{$2}$0" },
  { prefix = "den",   desc = "fraction with denominator",        body = "\\frac{$1}{$2}$0" },
  { prefix = "\\oo",  desc = "infinity",                         body = "\\infty" },
  { prefix = "to",    desc = "to",                               body = "\\(\\to\\)" },
  { prefix = "=>i",   desc = "implies",                          body = "\\implies" },
  { prefix = "=<",    desc = "implied by",                       body = "\\impliedby" },
  { prefix = "th",    desc = "therefore",                        body = "$\\therefore$ " },
  { prefix = "ap",    desc = "approx",                           body = "$\\approx$" },
  { prefix = "iff",   desc = "iff",                              body = "\\iff" },
  { prefix = "l(",    desc = "left( right)",                     body = "\\left( $1 \\right) $0" },
  { prefix = "l[",    desc = "square brackets",                  body = "\\left[ $1 \\right] $0" },
  { prefix = "l{",    desc = "curly brackets",                   body = "\\left\\{ $1 \\right\\} $0" },
  { prefix = "lng",   desc = "langle rangle",                    body = "\\langle $1 \\rangle$0" },
  { prefix = "bar",   desc = "bar",                              body = "\\overline{$1}$0" },
  { prefix = "hat",   desc = "hat",                              body = "\\hat{$1}$0" },
  { prefix = "bf",    desc = "bold text",                        body = "\\textbf{$1}$0" },
  { prefix = "it",    desc = "italic text",                      body = "\\textit{$1}$0" },
  { prefix = "ttt",   desc = "inline code",                      body = "\\texttt{$1}$0" },
  { prefix = "itbf",  desc = "bold, italic text",                body = "\\textit{\\textbf{$1}}$0" },
  { prefix = "mbf",   desc = "bold text",                        body = "\\mathbf{$1}$0" },
  { prefix = "ul",    desc = "underlined text",                  body = "\\underline{$1}$0" },
  { prefix = "...",   desc = "ldots",                            body = "\\ldots" },
  { prefix = "c.",    desc = "cdot",                             body = "\\cdot" },
  { prefix = "c..",   desc = "cdots",                            body = "\\cdots" },
  { prefix = "v..",   desc = "vdots",                            body = "\\vdots" },
  { prefix = "box",   desc = "boxed",                            body = "\\boxed{$1}$0" },
  { prefix = "pmat",  desc = "pmatrix",                          body = { "\\begin{pmatrix}", "\t$1", "\\end{pmatrix} $0" } },
  { prefix = "mat",   desc = "matrix",                           body = { "\\begin{matrix}", "\t$1", "\\end{matrix} $0" } },
  { prefix = "bmat",  desc = "bmatrix",                          body = { "\\begin{bmatrix}", "\t$1", "\\end{bmatrix} $0" } },
  { prefix = "sec",   desc = "section without number",           body = { "\\section*{$1}", "", "$0" } },
  { prefix = "ssec",  desc = "subsection without number",        body = { "\\subsection*{$1}", "", "$0" } },
  { prefix = "sssec", desc = "subsubsection without number",     body = { "\\subsubsection*{$1}", "", "$0" } },
  { prefix = "sct",   desc = "numbered section",                 body = { "\\section{$1}", "", "$0" } },
  { prefix = "ssct",  desc = "numbered sub section",             body = { "\\subsection{$1}", "", "$0" } },
  { prefix = "sssct", desc = "numbered sub sub section",         body = { "\\subsubsection{$1}", "", "$0" } },
  { prefix = "incg",  desc = "include basic graphic",            body = { "\\includegraphics[width=${1:}\\textwidth]{${2:}}", "$0" } },
  { prefix = "fig",   desc = "figure",                           body = { "", "\\begin{figure}[H]", "\t\\centering", "\t\\includegraphics[width=${1:}\\textwidth]{${2:}}", "\t\\caption{${3:}}", "\\end{figure}", "$0" } },
  {
    prefix = "2subfig",
    desc = "figure with two subfigures",
    body = {
      "",
      "\\begin{figure}[H]",
      "\t\\centering",
      "\t\\begin{subfigure}[b]{${1:}\\linewidth}",
      "\t\\includegraphics[width=\\linewidth]{${2:fig_path}} ",
      "\t\\caption{${3:}}",
      "\t\\end{subfigure}\\vspace{5mm}",
      "\t\\centering",
      "\t\\begin{subfigure}[b]{${4:}\\linewidth}",
      "\t\\includegraphics[width=\\linewidth]{${5:fig_path}}",
      "\t\\caption{${6:}}",
      "\t\\end{subfigure}",
      "\t\\caption{${7:}}",
      "\\end{figure}",
      "$0",
    },
  },
  {
    prefix = "3subfig",
    desc = "figure with three subfigures",
    body = {
      "\\begin{figure}[H]",
      "\t\\centering",
      "\t\\begin{subfigure}[b]{${1:}\\linewidth}",
      "\t\\includegraphics[width=\\linewidth]{${2:fig_path}} ",
      "\t\\caption{${3:}}",
      "\t\\end{subfigure}\\hspace{5mm}",
      "\t\\centering",
      "\t\\begin{subfigure}[b]{${4:}\\linewidth}",
      "\t\\includegraphics[width=\\linewidth]{${5:fig_path}}",
      "\t\\caption{${6:}}",
      "\t\\end{subfigure}\\hspace{5mm}",
      "\t\\centering",
      "\t\\begin{subfigure}[b]{${7:}\\linewidth}",
      "\t\\includegraphics[width=\\linewidth]{${8:fig_path}}",
      "\t\\caption{${9:}}",
      "\t\\end{subfigure}",
      "\t\\caption{${10:}}",
      "\\end{figure}",
      "$0",
    },
  },
  {
    prefix = "table",
    desc = "table environment",
    body = {
      "\\begin{table}[${1:htpb}]",
      "\t\\centering",
      "\t\\caption{${2:caption}}",
      "\t\\label{tab:${3:label}}",
      "\t\\begin{tabular}{${4:c}}",
      "\t$5",
      "\t\\end{tabular}",
      "\\end{table}",
      "$0",
    },
  },
  { prefix = "href", desc = "link to url", body = "\\href{${1:url}}{${2:text to display}} $0" },
  { prefix = "sch",  desc = "Schrodinger", body = "Schr\\\"{o}dinger $0" },
  {
    prefix = "begindoc",
    desc = "create basic template",
    body = {
      "\\documentclass[12pt]{article}",
      "",
      "\\usepackage[margin=2.0cm]{geometry}    %changes margin size",
      "\\usepackage{graphicx} % for adding pictures",
      "\\usepackage{float} %for positioning pictures",
      "\\usepackage{gensymb}",
      "\\usepackage{amssymb}",
      "\\usepackage{amsmath}",
      "\\usepackage{amsthm}",
      "\\usepackage{chngcntr}",
      "\\usepackage{hyperref}",
      "\\usepackage{subcaption}",
      "\\usepackage{listings}",
      "\\usepackage{algorithm}",
      "\\usepackage{algorithmic}",
      "\\usepackage[most]{tcolorbox}",
      "\\setlength{\\parindent}{0pt}",
      "",
      "\\newcommand{\\dd}{\\mathrm{d}}",
      "\\newcommand{\\R}{\\mathrm{R}}",
      "\\newcommand{\\C}{\\mathrm{C}}",
      "\\newcommand{\\Z}{\\mathrm{Z}}",
      "\\newcommand{\\Q}{\\mathrm{Q}}",
      "\\newcommand{\\prob}{\\mathrm{P}}",
      "\\newcommand{\\code}[1]{\\texttt{#1}}",
      "\\newcommand*\\mean[1]{\\bar{#1}}",
      "",
      "\\DeclareMathOperator*{\\minimize}{minimize}",
      "",
      "\\newtcblisting{codeblock}{",
      "  colback=gray!10,",
      "  colframe=gray!40,",
      "  listing only,",
      "  listing options={basicstyle=\\ttfamily\\small, mathescape},",
      "  left=4pt, right=4pt, top=4pt, bottom=4pt,",
      "  arc=2mm,",
      "  boxrule=0pt,",
      "}",
      "",
      "\\theoremstyle{definition}",
      "\\newtheorem{definition}{Definition}[section]",
      "",
      "\\begin{document}",
      "",
      "\\begin{huge}",
      "\t$1",
      "\\end{huge}",
      "",
      "\\section*{$2}",
      "",
      "$0",
      "",
      "\\end{document}",
    },
  },
}
