-- local ns = vim.api.nvim_create_namespace("colorcolumn")
-- local column = 100
--
-- vim.api.nvim_set_decoration_provider(ns, {
--   on_win = function(_, win, bufnr, topline, botline)
--     if vim.api.nvim_get_current_win() ~= win then return false end
--     if vim.bo[bufnr].buftype ~= "" then return false end
--     if not vim.bo[bufnr].modifiable then return false end
--
--     local target0 = column - 1
--     if vim.opt.filetype:get() == "tex" then
--       target0 = 81
--     end
--
--     for lnum = topline, botline - 1 do
--       -- Get the line and compute its *display* width (tabs, wide chars, etc.)
--       local line = vim.api.nvim_buf_get_lines(bufnr, lnum, lnum + 1, false)[1] or ""
--       local w = vim.fn.strdisplaywidth(line)
--
--       -- Only draw if the text ends before the target column
--       if w < target0 then
--         vim.api.nvim_buf_set_extmark(bufnr, ns, lnum, 0, {
--           ephemeral = true,
--           virt_text = { { "│", "WinSeparator" } },
--           virt_text_pos = "overlay",
--           virt_text_win_col = target0,
--           hl_mode = "combine",
--           priority = 1
--         })
--       end
--     end
--
--     return false
--   end,
-- })
