vim.cmd.hi('clear')
vim.g.colors_name = 'calmgray'

local palettes = {
  calmgray = {
    dark = {
      yellow         = '#e6bb86',
      popyellow      = '#FBB86C',
      earth          = '#bfa97a',
      orange         = '#e0a86c',
      pink           = '#e49ba7',
      ochre          = '#e87c69',
      scarlet        = '#d85959',
      wine           = '#a52929',
      tea            = '#a4bd84',
      aqua           = '#79ada7',
      turquoise      = '#7fa0af',
      flashlight     = '#add0ef',
      skyblue        = '#a5d5ff',
      cerulean       = '#86aadc',
      popblue        = '#46ACB8',
      lavender       = '#caafeb',
      purple         = '#a48fd1',
      magenta        = '#dc8ed3',
      pigeon         = '#8f9fbc',
      cumulonimbus   = '#557396',
      thunder        = '#23242a',   -- slightly lighter than bg
      white          = '#e5e5eb',
      smoke          = '#C6C6CE',   -- lighter for contrast
      beige          = '#b1aca7',
      steel          = '#767884',   -- lighter for contrast
      iron           = '#23242a',   -- matches thunder
      deepsea        = '#23242a',   -- matches thunder
      ocean          = '#1a1a1c',   -- slightly lighter than bg
      jeans          = '#141415',   -- main background
      space          = '#141415',   -- main background
      black          = '#0c0c0d',
      shadow         = '#0c0c0d',
      tea_blend      = '#2a2c2a',
      aqua_blend     = '#1c2324',
      purple_blend   = '#23242a',
      lavender_blend = '#2a2a3e',
      scarlet_blend  = '#2a1a1e',
      wine_blend     = '#1a1317',
      earth_blend    = '#23241a',
      smoke_blend    = '#1a1a1c',
      smoke_dark     = '#19191a',
      statusline     = '#23242a',
    },
    light = {
      yellow         = '#c88500',
      popyellow      = '#c88500',
      earth          = '#b48327',
      orange         = '#a84a24',
      pink           = '#df6d73',
      ochre          = '#c84b2b',
      scarlet        = '#d85959',
      wine           = '#a52929',
      tea            = '#5f8c3f',
      aqua           = '#3b8f84',
      turquoise      = '#29647a',
      flashlight     = '#97c0dc',
      skyblue        = '#4c99d4',
      cerulean       = '#3c70b4',
      popblue        = '#46ACB8',
      lavender       = '#9d7bca',
      purple         = '#8b71c7',
      magenta        = '#ac4ea1',
      pigeon         = '#6666a8',
      cumulonimbus   = '#486a91',
      thunder        = '#dfd6ce',
      white          = '#385372',
      smoke          = '#404553',
      beige          = '#385372',
      steel          = '#9a978a',
      iron           = '#b8b7b3',
      deepsea        = '#e6ded6',
      ocean          = '#f0e8e2',
      jeans          = '#faf4ed',
      space          = '#faf7ee',
      black          = '#efefef',
      shadow         = '#3c3935',
      tea_blend      = '#bdc8ad',
      aqua_blend     = '#c4cdc2',
      purple_blend   = '#e1dbe2',
      lavender_blend = '#bcb0cd',
      scarlet_blend  = '#e6b8b3',
      wine_blend     = '#e6c9c3',
      earth_blend    = '#ebe0ce',
      smoke_blend    = '#e4e4e2',
      smoke_dark     = '#e6ded6',
      statusline     = '#404553',
    }
  },
  darkergray = {
    dark = {
      yellow         = '#e9a04e',
      popyellow      = '#FBB86C',
      earth          = '#b1945e',
      orange         = '#e08c4e',
      pink           = '#e47a8b',
      ochre          = '#d86a54',
      scarlet        = '#c74a4a',
      wine           = '#922020',
      tea            = '#8ca76a',
      aqua           = '#5a9a8e',
      turquoise      = '#6a9bb0',
      flashlight     = '#8bbad3',
      skyblue        = '#86bfe6',
      cerulean       = '#46ACB8',
      popblue        = '#46ACB8',
      lavender       = '#b292d6',
      purple         = '#8c74b8',
      magenta        = '#c06bb6',
      pigeon         = '#6e86a6',
      cumulonimbus   = '#3e5d7a',
      thunder        = '#2d435d',
      white          = '#cfcfd6',
      smoke          = '#C0C0C9',
      beige          = '#978c7a',
      steel          = '#49546a',
      iron           = '#1d222b',
      deepsea        = '#1e2936',
      ocean          = '#1b222c',
      jeans          = '#151a24',
      space          = '#07080e',
      black          = '#07080e',
      shadow         = '#07080e',
      tea_blend      = '#2d3939',
      aqua_blend     = '#1a2328',
      purple_blend   = '#1b1e2c',
      lavender_blend = '#2c2c3e',
      scarlet_blend  = '#2c1a22',
      wine_blend     = '#1c1317',
      earth_blend    = '#1b1b1d',
      smoke_blend    = '#161a24',
      smoke_dark     = '#0E141D',
      statusline     = '#49546a',
    },
    light = {
      yellow         = '#c88500',
      popyellow      = '#c88500',
      earth          = '#b48327',
      orange         = '#a84a24',
      pink           = '#df6d73',
      ochre          = '#c84b2b',
      scarlet        = '#d85959',
      wine           = '#a52929',
      tea            = '#5f8c3f',
      aqua           = '#3b8f84',
      turquoise      = '#29647a',
      flashlight     = '#97c0dc',
      skyblue        = '#4c99d4',
      cerulean       = '#3c70b4',
      popblue        = '#46ACB8',
      lavender       = '#9d7bca',
      purple         = '#8b71c7',
      magenta        = '#ac4ea1',
      pigeon         = '#6666a8',
      cumulonimbus   = '#486a91',
      thunder        = '#e7e1b2',
      white          = '#385372',
      smoke          = '#404553',
      beige          = '#385372',
      steel          = '#b1a87a',
      iron           = '#a89f6e',
      deepsea        = '#e0d9a0',
      ocean          = '#d5cea3',
      jeans          = '#f2ecbc',
      space          = '#f2ecbc',
      black          = '#eeecd5',
      shadow         = '#cfc6a0',
      tea_blend      = '#bdc8ad',
      aqua_blend     = '#c4cdc2',
      purple_blend   = '#e1dbe2',
      lavender_blend = '#bcb0cd',
      scarlet_blend  = '#e6b8b3',
      wine_blend     = '#e6c9c3',
      earth_blend    = '#ebe0ce',
      smoke_blend    = '#e4e4e2',
      smoke_dark     = '#d5cea3',
      statusline     = '#404553',
    }
  }
}

local variant = vim.g.calmgray_variant or "calmgray"
local bg = vim.go.bg == "light" and "light" or "dark"
local c = palettes[variant][bg]

vim.g.terminal_color_0  = c.ocean
vim.g.terminal_color_1  = c.ochre
vim.g.terminal_color_2  = c.tea
vim.g.terminal_color_3  = c.yellow
vim.g.terminal_color_4  = c.cumulonimbus
vim.g.terminal_color_5  = c.lavender
vim.g.terminal_color_6  = c.aqua
vim.g.terminal_color_7  = c.white
vim.g.terminal_color_8  = c.white
vim.g.terminal_color_9  = c.ochre
vim.g.terminal_color_10 = c.tea
vim.g.terminal_color_11 = c.yellow
vim.g.terminal_color_12 = c.cumulonimbus
vim.g.terminal_color_13 = c.lavender
vim.g.terminal_color_14 = c.aqua
vim.g.terminal_color_15 = c.pigeon

-- Highlight groups
local hlgroups = {
  -- Common
  Normal = { fg = c.smoke, bg = c.jeans },
  NormalFloat = { fg = c.smoke, bg = c.jeans },
  NormalNC = { link = 'Normal' },
  ColorColumn = { bg = c.deepsea },
  Conceal = { fg = c.ochre },
  Cursor = { fg = c.space, bg = c.white },
  CursorColumn = { bg = c.ocean },
  CursorIM = { fg = c.space, bg = c.flashlight },
  CursorLine = { bg = c.ocean },
  CursorLineNr = { fg = c.popyellow, bg = c.ocean, bold = true },
  DebugPC = { bg = c.purple_blend },
  lCursor = { link = 'Cursor' },
  TermCursor = { fg = c.space, bg = c.orange },
  TermCursorNC = { fg = c.orange, bg = c.ocean },
  DiffAdd = { bg = c.aqua_blend },
  DiffAdded = { fg = c.tea, bg = c.aqua_blend },
  DiffChange = { bg = c.purple_blend },
  DiffDelete = { fg = c.wine, bg = c.wine_blend },
  DiffRemoved = { fg = c.scarlet, bg = c.wine_blend },
  DiffText = { bg = c.lavender_blend },
  Directory = { fg = c.pigeon },
  EndOfBuffer = { fg = c.iron },
  ErrorMsg = { fg = c.scarlet },
  FoldColumn = { fg = c.steel },
  Folded = { fg = c.steel, bg = c.ocean },
  FloatBorder = { fg = c.popblue, bg = c.jeans },
  FloatShadow = { bg = c.shadow, blend = 70 },
  FloatShadowThrough = { link = 'None' },
  HealthSuccess = { fg = c.tea },
  Search = { fg = c.orange, bg = c.thunder },
  IncSearch = { fg = c.turquoise, bg = c.orange, bold = true },
  CurSearch = { link = 'IncSearch' },
  LineNr = { fg = c.steel },
  ModeMsg = { fg = c.smoke },
  MoreMsg = { fg = c.aqua },
  MsgArea = { link = 'Normal' },
  MsgSeparator = { link = 'StatusLine' },
  MatchParen = { bg = c.thunder, bold = true },
  NonText = { fg = c.steel },
  Pmenu = { fg = c.smoke, bg = c.jeans },
  PmenuSbar = { bg = c.deepsea },
  PmenuSel = { fg = c.white, bg = c.thunder },
  PmenuThumb = { bg = c.orange },
  Question = { fg = c.smoke },
  QuickFixLine = { link = 'Visual' },
  SignColumn = { fg = c.smoke },
  SpecialKey = { fg = c.orange },
  SpellBad = { undercurl = true, sp = c.scarlet },
  SpellCap = { link = 'SpellBad' },
  SpellLocal = { link = 'SpellBad' },
  SpellRare = { link = 'SpellBad' },
  StatusLine = { fg = c.statusline, bg = c.smoke_dark },
  StatusLineNC = { fg = c.steel, bg = c.ocean },
  Substitute = { link = 'Search' },
  TabLine = { link = 'StatusLine' },
  TabLineFill = { fg = c.pigeon, bg = c.ocean },
  Title = { fg = c.pigeon, bold = true },
  VertSplit = { fg = c.ocean },
  Visual = { bg = c.thunder },
  VisualNOS = { link = 'Visual' },
  WarningMsg = { fg = c.yellow },
  Whitespace = { link = 'NonText' },
  WildMenu = { link = 'PmenuSel' },
  WinSeparator = { link = 'VertSplit' },
  WinBar = { fg = c.smoke },
  WinBarNC = { fg = c.pigeon },

  -- Syntax
  Comment = { fg = c.steel, italic = true },
  Constant = { fg = c.ochre },
  String = { fg = c.turquoise },
  DocumentKeyword = { fg = c.tea },
  Character = { fg = c.orange },
  Number = { fg = c.purple },
  Boolean = { fg = c.ochre },
  Array = { fg = c.orange },
  Float = { link = 'Number' },
  Identifier = { fg = c.smoke },
  Builtin = { fg = c.ochre },
  Field = { fg = c.pigeon },
  Enum = { fg = c.ochre },
  Namespace = { fg = c.ochre },
  Function = { fg = c.popyellow },
  Statement = { fg = c.lavender },
  Specifier = { fg = c.lavender },
  Object = { fg = c.lavender },
  Conditional = { fg = c.ochre },
  Repeat = { fg = c.magenta },
  Label = { fg = c.magenta },
  Operator = { fg = c.popblue },
  Keyword = { fg = c.popblue, italic = true },
  Exception = { fg = c.magenta },
  PreProc = { fg = c.turquoise },
  PreCondit = { link = 'PreProc' },
  Include = { link = 'PreProc' },
  Define = { link = 'PreProc' },
  Macro = { fg = c.ochre },
  Type = { fg = c.lavender },
  StorageClass = { link = 'Keyword' },
  Structure = { link = 'Type' },
  Typedef = { fg = c.beige },
  Special = { fg = c.orange },
  SpecialChar = { link = 'Special' },
  Tag = { fg = c.flashlight, underline = true },
  Delimiter = { fg = c.orange },
  Bracket = { fg = c.turquoise },
  SpecialComment = { link = 'SpecialChar' },
  Debug = { link = 'Special' },
  Underlined = { underline = true },
  Ignore = { fg = c.iron },
  Error = { fg = c.scarlet },
  Todo = { fg = c.black, bg = c.beige, bold = true },

  -- Treesitter syntax
  ['@field'] = { link = 'Field' },
  ['@property'] = { link = 'Field' },
  ['@annotation'] = { link = 'Operator' },
  ['@comment'] = { link = 'Comment' },
  ['@none'] = { link = 'None' },
  ['@preproc'] = { link = 'PreProc' },
  ['@define'] = { link = 'Define' },
  ['@operator'] = { link = 'Operator' },
  ['@punctuation.delimiter'] = { link = 'Delimiter' },
  ['@punctuation.bracket'] = { link = 'Bracket' },
  ['@punctuation.special'] = { fg = c.ochre },
  ['@string'] = { link = 'String' },
  ['@string.regex'] = { link = 'String' },
  ['@string.escape'] = { link = 'SpecialChar' },
  ['@string.special'] = { link = 'SpecialChar' },
  ['@character'] = { link = 'Character' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@boolean'] = { link = 'Boolean' },
  ['@number'] = { link = 'Number' },
  ['@float'] = { link = 'Float' },
  ['@function'] = { link = 'Function' },
  ['@function.call'] = { fg = c.ochre},
  ['@function.builtin'] = { link = 'Special' },
  ['@function.macro'] = { link = 'Macro' },
  ['@method'] = { link = 'Function' },
  ['@method.call'] = { link = 'Function' },
  ['@constructor'] = { link = 'Function' },
  ['@parameter'] = { link = 'Parameter' },
  ['@keyword'] = { link = 'Keyword' },
  ['@keyword.conditional'] = { fg = c.ochre },
  ['@keyword.function'] = { link = 'Keyword' },
  ['@keyword.return'] = { link = 'Keyword' },
  ['@conditional'] = { link = 'Conditional' },
  ['@repeat'] = { link = 'Repeat' },
  ['@debug'] = { link = 'Debug' },
  ['@label'] = { link = 'Keyword' },
  ['@include'] = { link = 'Include' },
  ['@exception'] = { link = 'Exception' },
  ['@type'] = { link = 'Type' },
  ['@type.Builtin'] = { link = 'Type' },
  ['@type.qualifier'] = { link = 'Type' },
  ['@type.definition'] = { link = 'Typedef' },
  ['@storageclass'] = { link = 'StorageClass' },
  ['@attribute'] = { link = 'Label' },
  ['@variable'] = { link = 'Identifier' },
  ['@variable.Builtin'] = { link = 'Builtin' },
  ['@variable.member'] = { fg = c.popyellow },
  ['@variable.parameter'] = { fg = c.turquoise },
  ['@constant'] = { link = 'Constant' },
  ['@constant.Builtin'] = { link = 'Constant' },
  ['@constant.macro'] = { link = 'Macro' },
  ['@markup.math'] = { fg = c.popyellow },
  ['@namespace'] = { link = 'Namespace' },
  ['@symbol'] = { link = 'Identifier' },
  ['@text'] = { link = 'String' },
  ['@text.title'] = { link = 'Title' },
  ['@text.literal'] = { link = 'String' },
  ['@text.uri'] = { link = 'htmlLink' },
  ['@text.math'] = { link = 'Special' },
  ['@text.environment'] = { link = 'Macro' },
  ['@text.environment.name'] = { link = 'Type' },
  ['@text.reference'] = { link = 'Constant' },
  ['@text.title.1.markdown'] = { link = 'markdownH1' },
  ['@text.title.2.markdown'] = { link = 'markdownH2' },
  ['@text.title.3.markdown'] = { link = 'markdownH3' },
  ['@text.title.4.markdown'] = { link = 'markdownH4' },
  ['@text.title.5.markdown'] = { link = 'markdownH5' },
  ['@text.title.6.markdown'] = { link = 'markdownH6' },
  ['@text.title.1.marker.markdown'] = { link = 'markdownH1Delimiter' },
  ['@text.title.2.marker.markdown'] = { link = 'markdownH2Delimiter' },
  ['@text.title.3.marker.markdown'] = { link = 'markdownH3Delimiter' },
  ['@text.title.4.marker.markdown'] = { link = 'markdownH4Delimiter' },
  ['@text.title.5.marker.markdown'] = { link = 'markdownH5Delimiter' },
  ['@text.title.6.marker.markdown'] = { link = 'markdownH6Delimiter' },
  ['@text.todo'] = { link = 'Todo' },
  ['@text.todo.unchecked'] = { link = 'Todo' },
  ['@text.todo.checked'] = { link = 'Done' },
  ['@text.note'] = { link = 'SpecialComment' },
  ['@text.warning'] = { link = 'WarningMsg' },
  ['@text.danger'] = { link = 'ErrorMsg' },
  ['@text.diff.add'] = { link = 'DiffAdded' },
  ['@text.diff.delete'] = { link = 'DiffRemoved' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.attribute'] = { link = 'Identifier' },
  ['@tag.delimiter'] = { link = 'Delimiter' },
  ['@text.strong'] = { bold = true },
  ['@text.strike'] = { strikethrough = true },
  ['@text.emphasis'] = { fg = c.beige, bold = true, italic = true, },
  ['@text.underline'] = { underline = true },
  ['@keyword.operator'] = { link = 'Operator' },

  TreesitterContext = { bg = c.ocean },

  -- LSP semantic
  ['@lsp.type.enum'] = { link = 'Type' },
  ['@lsp.type.type'] = { link = 'Type' },
  ['@lsp.type.class'] = { link = 'Structure' },
  ['@lsp.type.struct'] = { link = 'Structure' },
  ['@lsp.type.macro'] = { link = 'Macro' },
  ['@lsp.type.method'] = { link = 'Function' },
  ['@lsp.type.comment'] = { link = 'Comment' },
  ['@lsp.type.function'] = { link = 'Function' },
  ['@lsp.type.property'] = { link = 'Field' },
  ['@lsp.type.variable'] = { link = 'Variable' },
  ['@lsp.type.decorator'] = { link = 'Label' },
  ['@lsp.type.interface'] = { link = 'Structure' },
  ['@lsp.type.namespace'] = { link = 'Namespace' },
  ['@lsp.type.parameter'] = { link = 'Parameter' },
  ['@lsp.type.enumMember'] = { link = 'Enum' },
  ['@lsp.type.typeParameter'] = { link = 'Parameter' },
  ['@lsp.typemod.keyword.documentation'] = { link = 'DocumentKeyword' },
  ['@lsp.typemod.function.defaultLibrary'] = { link = 'Special' },
  ['@lsp.typemod.variable.defaultLibrary'] = { link = 'Builtin' },
  ['@lsp.typemod.variable.global'] = { link = 'Identifier' },

  -- LSP
  LspReferenceText = { link = 'Visual' },
  LspReferenceRead = { link = 'LspReferenceText' },
  LspReferenceWrite = { link = 'LspReferenceText' },
  LspSignatureActiveParameter = { link = 'IncSearch' },
  LspInfoBorder = { link = 'FloatBorder' },
  LspInlayHint = { link = 'DiagnosticVirtualTextHint' },

  -- Diagnostic
  DiagnosticOk = { fg = c.tea },
  DiagnosticError = { fg = c.wine },
  DiagnosticWarn = { fg = c.earth },
  DiagnosticInfo = { fg = c.smoke },
  DiagnosticHint = { fg = c.pigeon },
  DiagnosticVirtualTextOk = { fg = c.tea, bg = c.tea_blend },
  DiagnosticVirtualTextError = { fg = c.wine, bg = c.wine_blend },
  DiagnosticVirtualTextWarn = { fg = c.earth, bg = c.earth_blend },
  DiagnosticVirtualTextInfo = { fg = c.tea, bg = c.ocean },
  DiagnosticVirtualTextHint = { fg = c.popblue, bg = c.deepsea },
  DiagnosticUnderlineOk = { underline = true, sp = c.tea },
  DiagnosticUnderlineError = { undercurl = true, sp = c.wine },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.earth },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.flashlight },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.pigeon },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },

  -- Filetype (HTML, Markdown, etc.)
  htmlArg = { fg = c.pigeon },
  htmlBold = { bold = true },
  htmlBoldItalic = { bold = true, italic = true },
  htmlTag = { fg = c.smoke },
  htmlTagName = { link = 'Tag' },
  htmlSpecialTagName = { fg = c.yellow },
  htmlEndTag = { fg = c.yellow },
  htmlH1 = { fg = c.yellow, bold = true },
  htmlH2 = { fg = c.ochre, bold = true },
  htmlH3 = { fg = c.pink, bold = true },
  htmlH4 = { fg = c.lavender, bold = true },
  htmlH5 = { fg = c.cerulean, bold = true },
  htmlH6 = { fg = c.aqua, bold = true },
  htmlItalic = { italic = true },
  htmlLink = { fg = c.flashlight, underline = true },
  htmlSpecialChar = { fg = c.beige },
  htmlTitle = { fg = c.pigeon },

  jsonKeyword = { link = 'Keyword' },
  jsonBraces = { fg = c.smoke },

  markdownBold = { fg = c.aqua, bold = true },
  markdownBoldItalic = { fg = c.skyblue, bold = true, italic = true },
  markdownCode = { fg = c.pigeon },
  markdownError = { link = 'None' },
  markdownEscape = { link = 'None' },
  markdownListMarker = { fg = c.orange },
  markdownH1 = { link = 'htmlH1' },
  markdownH2 = { link = 'htmlH2' },
  markdownH3 = { link = 'htmlH3' },
  markdownH4 = { link = 'htmlH4' },
  markdownH5 = { link = 'htmlH5' },
  markdownH6 = { link = 'htmlH6' },

  shDeref = { link = 'Macro' },
  shDerefVar = { link = 'Macro' },

  gitHash = { fg = c.pigeon },

  helpHeader = { fg = c.pigeon, bold = true },
  helpSectionDelim = { fg = c.ochre, bold = true },
  helpCommand = { fg = c.turquoise },
  helpBacktick = { fg = c.turquoise },

  manBold = { fg = c.ochre, bold = true },
  manItalic = { fg = c.turquoise, italic = true },
  manOptionDesc = { fg = c.ochre },
  manReference = { link = 'htmlLink' },
  manSectionHeading = { link = 'manBold' },
  manUnderline = { fg = c.cerulean },

  -- Plugins
  netrwClassify = { link = 'Directory' },

  BlinkCmpMenu = { fg = c.smoke, bg = c.jeans },
  BlinkCmpMenuBorder = { fg = c.popblue, bg = c.jeans},
  BlinkCmpDocBorder = { fg = c.popyellow, bg = c.jeans },
  BlinkCmpSignatureHelp = { link = "BlinkCmpMenu" },
  BlinkCmpSignatureHelpBorder = { link = "BlinkCmpMenuBorder" },
  BlinkCmpSignatureHelpActiveParameter = { bg = c.thunder },
  BlinkCmpScrollBarGutter = { bg = c.jeans },

  CmpItemAbbr = { fg = c.smoke },
  CmpItemAbbrDeprecated = { strikethrough = true },
  CmpItemAbbrMatch = { fg = c.white, bold = true },
  CmpItemAbbrMatchFuzzy = { link = 'CmpItemAbbrMatch' },
  CmpItemKindText = { link = 'String' },
  CmpItemKindMethod = { link = 'Function' },
  CmpItemKindFunction = { link = 'Function' },
  CmpItemKindConstructor = { link = 'Function' },
  CmpItemKindField = { fg = c.purple },
  CmpItemKindProperty = { link = 'CmpItemKindField' },
  CmpItemKindVariable = { fg = c.aqua },
  CmpItemKindReference = { link = 'CmpItemKindVariable' },
  CmpItemKindModule = { fg = c.magenta },
  CmpItemKindEnum = { fg = c.ochre },
  CmpItemKindEnumMember = { link = 'CmpItemKindEnum' },
  CmpItemKindKeyword = { link = 'Keyword' },
  CmpItemKindOperator = { link = 'Operator' },
  CmpItemKindSnippet = { fg = c.tea },
  CmpItemKindColor = { fg = c.pink },
  CmpItemKindConstant = { link = 'Constant' },
  CmpItemKindCopilot = { fg = c.magenta },
  CmpItemKindValue = { link = 'Number' },
  CmpItemKindClass = { link = 'Type' },
  CmpItemKindStruct = { link = 'Type' },
  CmpItemKindEvent = { fg = c.flashlight },
  CmpItemKindInterface = { fg = c.flashlight },
  CmpItemKindFile = { link = 'DevIconDefault' },
  CmpItemKindFolder = { link = 'Directory' },
  CmpItemKindUnit = { fg = c.cerulean },
  CmpItemKind = { fg = c.smoke },
  CmpItemMenu = { link = 'Pmenu' },
  CmpVirtualText = { fg = c.steel, italic = true },
  CmpBorder = { link = 'FloatBorder' },
  CmpDocBorder = { fg = c.yellow },

  GitSignsAdd = { fg = c.tea },
  GitSignsAddInline = { fg = c.tea, bg = c.tea_blend },
  GitSignsAddLnInline = { fg = c.tea, bg = c.tea_blend },
  GitSignsAddPreview = { link = 'DiffAdded' },
  GitSignsChange = { fg = c.turquoise },
  GitSignsChangeInline = { fg = c.lavender, bg = c.lavender_blend },
  GitSignsChangeLnInline = { fg = c.lavender, bg = c.lavender_blend, },
  GitSignsCurrentLineBlame = { fg = c.smoke, bg = c.smoke_blend },
  GitSignsDelete = { fg = c.wine },
  GitSignsDeleteInline = { fg = c.scarlet, bg = c.scarlet_blend },
  GitSignsDeleteLnInline = { fg = c.scarlet, bg = c.scarlet_blend },
  GitSignsDeletePreview = { fg = c.scarlet, bg = c.wine_blend },
  GitSignsDeleteVirtLnInLine = { fg = c.scarlet, bg = c.scarlet_blend, },
  GitSignsUntracked = { fg = c.scarlet_blend },
  GitSignsUntrackedLn = { bg = c.scarlet_blend },
  GitSignsUntrackedNr = { fg = c.pink },

  fugitiveHash = { link = 'gitHash' },
  fugitiveHeader = { link = 'Title' },
  fugitiveHeading = { fg = c.orange, bold = true },
  fugitiveHelpTag = { fg = c.orange },
  fugitiveSymbolicRef = { fg = c.yellow },
  fugitiveStagedModifier = { fg = c.tea, bold = true },
  fugitiveUnstagedModifier = { fg = c.scarlet, bold = true },
  fugitiveUntrackedModifier = { fg = c.pigeon, bold = true },
  fugitiveStagedHeading = { fg = c.aqua, bold = true },
  fugitiveUnstagedHeading = { fg = c.ochre, bold = true },
  fugitiveUntrackedHeading = { fg = c.lavender, bold = true },

  MiniIndentscopeSymbol = { fg = c.deepsea },

  NeoTreeNormal = { bg = c.smoke_dark },
  NeoTreeNormalNC = { link =  "NeoTreeNormal" },
  NeoTreeDimText = { fg = c.steel },
  NeoTreeWinSeparator = { fg = c.jeans, bg = c.jeans },
  NeoTreeCursorLine = { bg = c.ocean },

  NoiceCmdlinePopupBorder= { fg = c.popyellow, bg = c.jeans },
  NoiceCmdlinePopupBorderCmdline  = { fg = c.popblue, bg = c.jeans },

  NotifyERRORBorder = { fg = c.wine },
  NotifyWARNBorder = { fg = c.popyellow },
  NotifyINFOBorder = { fg = c.popblue },
  NotifyDEBUGBorder = { fg = c.lavender },
  NotifyTRACEBorder = { fg = c.tea },
  NotifyERRORIcon = { link = "NotifyERRORBorder" },
  NotifyWARNIcon = { link = "NotifyWARNBorder" },
  NotifyINFOIcon = { link = "NotifyINFOBorder" },
  NotifyDEBUGIcon = { link = "NotifyDEBUGBorder" },
  NotifyTRACEIcon = { link = "NotifyTRACEBorder" },
  NotifyERRORTitle =  { link = 'NotifyERRORBorder' },
  NotifyWARNTitle = { link = 'NotifyWARNBorder' },
  NotifyINFOTitle = { link = 'NotifyINFOBorder' },
  NotifyDEBUGTitle =  { link = 'NotifyDEBUGBorder' },
  NotifyTRACETitle =  { link = 'NotifyTRACEBorder' },
  NotifyERRORBody = { link = "Normal" },
  NotifyWARNBody = { link = "Normal" },
  NotifyINFOBody = { link = "Normal" },
  NotifyDEBUGBody = { link = "Normal" },
  NotifyTRACEBody = { link = "Normal" },

  UIMessageInfo = { fg = c.tea },
  UIMessageInfoSign = { link = "NotifyINFOIcon" },

  TelescopeBorder = { fg = c.popyellow, bg = c.jeans },
  TelescopePromptBorder = { fg = c.popblue, bg = c.jeans },
  TelescopePreviewBorder = { fg = c.popblue, bg = c.jeans },
  TelescopePreviewTitle = { link = 'TelescopePreviewBorder' },
  TelescopePromptTitle = { fg = c.popblue, bg = c.jeans },
  TelescopeSelectionCaret = { fg = c.popyellow, bg = c.deepsea },

  DapUIBreakpointsCurrentLine = { link = 'CursorLineNr' },
  DapUIBreakpointsInfo = { fg = c.tea },
  DapUIBreakpointsPath = { link = 'Directory' },
  DapUICurrentFrameName = { fg = c.tea, bold = true },
  DapUIDecoration = { fg = c.yellow },
  DapUIFloatBorder = { link = 'FloatBorder' },
  DapUINormalFloat = { link = 'NormalFloat' },
  DapUILineNumber = { link = 'LineNr' },
  DapUIModifiedValue = { fg = c.skyblue, bold = true },
  DapUIPlayPause = { fg = c.tea },
  DapUIPlayPauseNC = { fg = c.tea },
  DapUIRestart = { fg = c.tea },
  DapUIRestartNC = { fg = c.tea },
  DapUIScope = { fg = c.orange },
  DapUISource = { link = 'Directory' },
  DapUIStepBack = { fg = c.lavender },
  DapUIStepBackRC = { fg = c.lavender },
  DapUIStepInto = { fg = c.lavender },
  DapUIStepIntoRC = { fg = c.lavender },
  DapUIStepOut = { fg = c.lavender },
  DapUIStepOutRC = { fg = c.lavender },
  DapUIStepOver = { fg = c.lavender },
  DapUIStepOverRC = { fg = c.lavender },
  DapUIStop = { fg = c.scarlet },
  DapUIStopNC = { fg = c.scarlet },
  DapUIStoppedThread = { fg = c.tea },
  DapUIThread = { fg = c.aqua },
  DapUIType = { link = 'Type' },
  DapUIVariable = { link = 'Identifier' },
  DapUIWatchesEmpty = { link = 'Comment' },
  DapUIWatchesError = { link = 'Error' },
  DapUIWatchesValue = { fg = c.orange },

  texArg = { fg = c.ochre },
  texArgNew = { fg = c.skyblue },
  texCmd = { fg = c.popblue },
  texCmdPackage = { fg = c.popyellow },
  texCmdNewCmd = { fg = c.ochre },
  texCmdBib = { link = 'texCmd' },
  texCmdDeclmathoper = { fg = c.cerulean },
  texCmdClass = { link = 'texCmd' },
  texCmdDef = { link = 'texCmd' },
  texCmdE3 = { link = 'texCmd' },
  texCmdEnv = { fg = c.cerulean },
  texEnvArgName = { fg = c.pigeon },
  texCmdEnvM = { link = 'texCmd' },
  texCmdError = { link = 'ErrorMsg' },
  texCmdFatal = { link = 'ErrorMsg' },
  texCmdGreek = { link = 'texCmd' },
  texCmdInput = { fg = c.yellow },
  texCmdItem = { fg = c.ochre },
  texCmdLet = { link = 'texCmd' },
  texCmdMath = { link = 'texCmd' },
  texCmdMathEnv = { fg = c.pigeon },
  texCmdNew = { link = 'texCmd' },
  texCmdPart = { fg = c.pigeon },
  texCmdRef = { link = 'texCmd' },
  texCmdSize = { link = 'texCmd' },
  texCmdStyle = { link = 'texCmd' },
  texCmdTitle = { link = 'texCmd' },
  texCmdTodo = { link = 'texCmd' },
  texCmdType = { link = 'texCmd' },
  texCmdVerb = { link = 'texCmd' },
  texComment = { link = 'Comment' },
  texDefParm = { link = 'Keyword' },
  texDelim = { fg = c.flashlight },
  texE3Cmd = { link = 'texCmd' },
  texE3Delim = { link = 'texDelim' },
  texE3Opt = { link = 'texOpt' },
  texE3Parm = { link = 'texParm' },
  texE3Type = { link = 'texCmd' },
  texEnvOpt = { link = 'texOpt' },
  texError = { link = 'ErrorMsg' },
  texFileArg = { link = 'Directory' },
  texFileOpt = { fg = c.ochre },
  texFilesArg = { link = 'texFileArg' },
  texFilesOpt = { link = 'texFileOpt' },
  texLength = { fg = c.lavender },
  texLigature = { fg = c.pigeon },
  texOpt = { fg = c.ochre },
  texItemLabel = { fg = c.popyellow },
  texItemLabelConcealed = { fg = c.popyellow },
  texConcealedArg = { fg = c.ochre },
  texOptEqual = { fg = c.orange },
  texOptSep = { fg = c.orange },
  texParm = { fg = c.pigeon },
  texRefArg = { fg = c.lavender },
  texRefOpt = { link = 'texOpt' },
  texSymbol = { fg = c.pigeon },
  texTitleArg = { fg = c.popyellow },
  texVerbZone = { fg = c.pigeon },
  texZone = { fg = c.pigeon },
  texTCBZone = { fg = c.tea },
  texMathArg = { fg = c.pigeon },
  texMathCmd = { fg = c.cerulean },
  texMathSub = { fg = c.pigeon },
  texMathOper = { fg = c.popblue },
  texMathZone = { fg = c.yellow },
  texMathDelim = { fg = c.flashlight },
  texMathError = { link = 'Error' },
  texMathGroup = { fg = c.pigeon },
  texMathSuper = { fg = c.lavender },
  texMathSymbol = { fg = c.popblue },
  texMathZoneLD = { fg = c.lavender },
  texMathZoneLI = { fg = c.flashlight },
  texMathZoneTD = { fg = c.flashlight },
  texMathZoneTI = { fg = c.flashlight },
  texMathCmdText = { link = 'texCmd' },
  texMathZoneEnv = { fg = c.flashlight },
  texMathEnvBgnEnd = { fg = c.popyellow },
  texPartArgTitle = { fg = c.yellow, italic = true },
  texMathArrayArg = { fg = c.yellow },
  texMathCmdStyle = { link = 'texCmd' },
  texMathDelimMod = { fg = c.turquoise },
  texMathSuperSub = { fg = c.ochre },
  texMathDelimZone = { fg = c.lavender },
  texMathStyleBold = { fg = c.smoke, bold = true },
  texMathStyleItal = { fg = c.smoke, italic = true },
  texMathEnvArgName = { fg = c.popblue },
  texMathErrorDelim = { link = 'Error' },
  texMathDelimZoneLD = { fg = c.lavender },
  texMathDelimZoneLI = { fg = c.lavender },
  texMathDelimZoneTD = { fg = c.lavender },
  texMathDelimZoneTI = { fg = c.lavender },
  texMathZoneEnsured = { fg = c.pigeon },
  texMathCmdStyleBold = { fg = c.yellow, bold = true },
  texMathCmdStyleItal = { fg = c.yellow, italic = true },
  texMathStyleConcArg = { fg = c.pigeon },
  texMathZoneEnvStarred = { fg = c.pigeon },

  LazyDir = { link = 'Directory' },
  LazyUrl = { link = 'htmlLink' },
  LazySpecial = { fg = c.orange },
  LazyCommit = { fg = c.tea },
  LazyReasonFt = { fg = c.pigeon },
  LazyReasonCmd = { fg = c.yellow },
  LazyReasonPlugin = { fg = c.turquoise },
  LazyReasonSource = { fg = c.orange },
  LazyReasonRuntime = { fg = c.lavender },
  LazyReasonEvent = { fg = c.flashlight },
  LazyReasonKeys = { fg = c.pink },
  LazyButton = { bg = c.ocean },
  LazyButtonActive = { bg = c.thunder, bold = true },
  LazyH1 = { fg = c.space, bg = c.yellow, bold = true },

  CopilotSuggestion = { fg = c.steel, italic = true },
  CopilotAnnotation = { fg = c.steel, italic = true },

  StatusLineDiagnosticError = { fg = c.wine, bg = c.smoke_dark },
  StatusLineDiagnosticHint = { fg = c.pigeon, bg = c.smoke_dark },
  StatusLineDiagnosticInfo = { fg = c.smoke, bg = c.smoke_dark },
  StatusLineDiagnosticWarn = { fg = c.earth, bg = c.smoke_dark },
  StatusLineGitAdded = { fg = c.tea, bg = c.smoke_dark },
  StatusLineGitChanged = { fg = c.lavender, bg = c.smoke_dark },
  StatusLineGitRemoved = { fg = c.scarlet, bg = c.smoke_dark },
  StatusLineHeaderModified = { fg = c.ochre },

  GlanceBorderTop = { link = 'WinSeparator' },
  GlancePreviewBorderBottom = { link = 'GlanceBorderTop' },
  GlanceListBorderBottom = { link = 'GlanceBorderTop' },
  GlanceFoldIcon = { link = 'Comment' },
  GlanceListCount = { fg = c.jeans, bg = c.pigeon },
  GlanceListCursorLine = { bg = c.deepsea },
  GlanceListNormal = { bg = c.deepsea },
  GlanceListMatch = { bg = c.thunder, bold = true },
  GlancePreviewNormal = { link = 'Pmenu' },
  GlanceWinBarFilename = { fg = c.pigeon, bg = c.deepsea, bold = true },
  GlanceWinBarFilepath = { fg = c.pigeon, bg = c.deepsea },
  GlanceWinBarTitle = { fg = c.pigeon, bg = c.deepsea, bold = true },

  -- Extra
  Yellow = { fg = c.yellow },
  Earth = { fg = c.earth },
  Orange = { fg = c.orange },
  Scarlet = { fg = c.scarlet },
  Ochre = { fg = c.ochre },
  Wine = { fg = c.wine },
  Pink = { fg = c.pink },
  Tea = { fg = c.tea },
  Flashlight = { fg = c.flashlight },
  Aqua = { fg = c.aqua },
  Cerulean = { fg = c.cerulean },
  SkyBlue = { fg = c.skyblue },
  Turquoise = { fg = c.turquoise },
  Lavender = { fg = c.lavender },
  Magenta = { fg = c.magenta },
  Purple = { fg = c.purple },
  Thunder = { fg = c.thunder },
  White = { fg = c.white },
  Beige = { fg = c.beige },
  Pigeon = { fg = c.pigeon },
  Popblue = { fg = c.popblue },
  Popyellow = { fg = c.popyellow },
  Steel = { fg = c.steel },
  Smoke = { fg = c.smoke },
  Iron = { fg = c.iron },
  Deepsea = { fg = c.deepsea },
  Ocean = { fg = c.ocean },
  Space = { fg = c.space },
  Black = { fg = c.black },
}

for hlgroup_name, hlgroup_attr in pairs(hlgroups) do
  vim.api.nvim_set_hl(0, hlgroup_name, hlgroup_attr)
end

-- vim:ts=2:sw=2:sts=2:fdm=marker:fdl=0

