require("colorbuddy").colorscheme "colourscheme"

local colorbuddy = require "colorbuddy"
local Color = colorbuddy.Color
local Group = colorbuddy.Group
local c = colorbuddy.colors
local g = colorbuddy.groups
local s = colorbuddy.styles

Color.new("white", "#f2e5bc")
Color.new("lightgray", "#2b2b2b")
Color.new("gray1", "#151515")
Color.new("darkgray", "#0f0f0f")
Color.new("red", "#cc6666")
Color.new("pink", "#fef601")
Color.new("green", "#99cc99")
Color.new("yellow", "#f8fe7a")
-- Color.new("yellow", "#FCE094")
Color.new("blue", "#81a2be")
Color.new("popblue", "#46ACB8")
Color.new("aqua", "#8ec07c")
Color.new("cyan", "#8abeb7")
Color.new("purple", "#8e6fbd")
Color.new("violet", "#b294bb")
Color.new("orange", "#de935f")
Color.new("ochre", "#e87c69")
Color.new("brown", "#a3685a")

Color.new("seagreen", "#698b69")
Color.new("turquoise", "#698b69")

local background_string = "#111111"
Color.new("background", background_string)
Color.new("gray0", background_string)

Group.new("Normal", c.superwhite, c.gray0)
Group.new("LineNr", c.lightgray, c.gray0)
Group.new("Conceal", c.ochre, c.gray0)
Group.new("Comment", g.nontext.fg:light(), nil, s.italic)
Group.new("VertSplit", c.gray0, c.gray0, s.none)
Group.new("WinSeparator", c.lightgray:light(), nil, s.none)
Group.new("DiagnosticUnderlineError", c.red, nil, s.undercurl)
Group.new("DiagnosticUnderlineWarn", nil, nil, s.undercurl, c.yellow.light())
Group.new("DiagnosticUnderlineInfo", nil, nil, s.undercurl, c.blue)
Group.new("DiagnosticUnderlineeHint", nil, nil, s.undercurl, c.aqua)
Group.new("DiagnosticUnderlineeOk", nil, nil, s.undercurl, c.green)
Group.new("MatchParen", nil, c.lightgray:light(), s.none)
Group.new("Pmenu", nil, nil, s.none)
Group.new("NormalFloat", nil, nil, s.none)
Group.new("FloatBorder", nil, nil, s.none)
Group.new("EndOfBuffer", c.gray0, nil, s.none)
Group.new("ModeMsg", c.blue, nil, s.none)
Group.new("Visual", nil, c.blue:dark():dark():dark(), s.none)
Group.new("TabLine", g.cursorline.fg, c.gray0, s.none)
Group.new("TabLineFill", g.cursorline.fg, c.lightgray, s.none)
Group.new("TabLineSel", g.statusline.fg, g.statusline.bg, s.none)
Group.new("StatusLineHeaderModified", nil, c.blue:light(), s.none)
Group.new("LspReferenceText", nil, g.Visual.bg, s.none)
Group.new("LspReferenceRead", nil, g.Visual.bg, s.none)
Group.new("LspReferenceWrite", nil, g.Visual.bg, s.none)
Group.new("Number", c.ochre, nil, s.none)
Group.new("Boolean", c.ochre, nil, s.none)

Group.new("@constant", c.orange, nil, s.none)
Group.new("@function", c.yellow, nil, s.none)
Group.new("@function.builtin", c.yellow, nil, s.none)
Group.new("@function.method", c.yellow, nil, s.none)
Group.new("@function.call", c.blue, nil, s.bold)
Group.new("@function.method.call", c.yellow, nil, s.none)
Group.new("@function.bracket", g.Normal, g.Normal)
Group.new("@keyword", c.violet, nil, s.none)
Group.new("@keyword.function", c.blue, nil, s.italic)
Group.new("@keyword.faded", g.nontext.fg:light(), nil, s.none)
Group.new("@keyword.repeat", c.blue, nil, s.none)
Group.new("@keyword.return", c.violet, nil, s.italic)
Group.new("@keyword.exception", c.blue, nil, s.none)
Group.new("@type.builtin", c.violet, nil, s.bold)
Group.new("@module", c.blue)
Group.new("@module.builtin", c.blue)
Group.new("@property", c.blue)
Group.new("@variable", c.superwhite, nil)
Group.new("@variable.builtin", c.purple:light():light(), g.Normal)
Group.new("@variable.member", c.superwhite, nil)
Group.new("@variable.parameter", c.blue, nil)
Group.new("@constructor", c.violet, nil)
Group.new("@punctuation", c.superwhite, nil)
Group.new("@punctuation.special", c.violet, nil)
Group.new("@string", c.green, nil, s.italic)

Group.new("texCmd", c.ochre, nil, s.italic)
Group.new("texCmdEnv", c.violet, nil, s.none)
Group.new("texCmdPackage", c.violet, nil, s.italic)
Group.new("texCmdPart", c.blue, nil, s.italic)
Group.new("texMathCmd", c.white, nil, s.italic)
Group.new("texMathDelim", c.blue:light(), nil, s.none)
Group.new("texFilesArg", c.blue, nil, s.italic)
Group.new("texCmdNewcmd", c.blue, nil, s.none)
Group.new("texNewCmdArgName", c.aqua, nil, s.none)
Group.new("texTCBZone", c.aqua, nil, s.italic)
Group.new("texEnvArgName", c.blue, nil, s.none)
Group.new("texPartArgTitle", c.orange:light(), nil, s.none)
Group.new("texMathEnvArgName", c.blue, nil, s.none)
Group.new("texMathZoneEnv", c.blue, nil, s.none)
Group.new("texMathOper", c.blue, nil, s.none)
Group.new("texMathGroup", c.blue:light(), nil, s.none)
Group.new("texMathSymbol", c.white, nil, s.none)

Group.new("@lsp.type.method", c.yellow, nil, s.none)
Group.new("@lsp.type.namespace", c.yellow, nil, s.none)
Group.new("@lsp.typemod.function.defaultLibrary.lua", c.blue, nil, s.none)

Group.new("TreesitterContext", nil, g.nontext.fg.light(), s.none)

Group.new("@function.call.lua", c.blue:dark(), nil, nil)
Group.new("@variable.builtin.python", c.red, g.Normal)
