-- Simplified modus themes for Neovim
-- Original author: Protesilaos Stavrou (https://protesilaos.com)
-- Neovim implementation and palette derived from https://github.com/miikanissi/modus-themes.nvim
-- Implementation by Aymen Hafeez (2026)

local palettes = {
  light = {
    bg_main = "#ffffff",
    bg_dim = "#f2f2f4",
    bg_alt = "#e8e8ea",
    border = "#929298",
    border_highlight = "#2e2e32",
    bg_hl_line = "#cdd8e2",
    fg_main = "#000000",
    fg_dim = "#595959",
    fg_alt = "#193668",
    red = "#a60000",
    red_warmer = "#972500",
    red_cooler = "#a0132f",
    red_faint = "#7f0000",
    green = "#006800",
    green_warmer = "#316500",
    green_cooler = "#00663f",
    green_faint = "#2a5045",
    yellow = "#6f5500",
    yellow_warmer = "#884900",
    yellow_cooler = "#7a4f2f",
    yellow_faint = "#624416",
    blue = "#0031a9",
    blue_warmer = "#3548cf",
    blue_cooler = "#0000b0",
    blue_faint = "#003497",
    magenta = "#721045",
    magenta_warmer = "#8f0075",
    magenta_cooler = "#531ab6",
    magenta_faint = "#7c318f",
    cyan = "#005e8b",
    cyan_warmer = "#3f578f",
    cyan_cooler = "#005f5f",
    cyan_faint = "#005077",
    rust = "#8a290f",
    gold = "#80601f",
    olive = "#56692d",
    slate = "#2f3f83",
    indigo = "#4a3a8a",
    maroon = "#731c52",
    pink = "#7b435c",
    red_intense = "#d00000",
    green_intense = "#008900",
    yellow_intense = "#808000",
    blue_intense = "#0000ff",
    magenta_intense = "#dd22dd",
    cyan_intense = "#008899",
    bg_red_intense = "#ff8f88",
    bg_green_intense = "#8adf80",
    bg_yellow_intense = "#f3d000",
    bg_blue_intense = "#bfc9ff",
    bg_magenta_intense = "#dfa0f0",
    bg_cyan_intense = "#a4d5f9",
    bg_red_subtle = "#ffcfbf",
    bg_green_subtle = "#b3fabf",
    bg_yellow_subtle = "#fff576",
    bg_blue_subtle = "#ccdfff",
    bg_magenta_subtle = "#ffddff",
    bg_cyan_subtle = "#bfefff",
    bg_red_nuanced = "#fff5f5",
    bg_green_nuanced = "#f0faf0",
    bg_yellow_nuanced = "#fff8e0",
    bg_blue_nuanced = "#f5f5ff",
    bg_magenta_nuanced = "#fdf5ff",
    bg_cyan_nuanced = "#f0f8fc",
    bg_completion = "#c0deff",
    bg_paren_match = "#5fcfff",
    bg_paren_expression = "#efd3f5",
    bg_char_0 = "#7feaff",
    bg_char_1 = "#ffaaff",
    bg_char_2 = "#dff000",
    bg_active = "#e0e0e2",
    fg_active = "#0a0a0a",
    bg_inactive = "#eaeaea",
    fg_inactive = "#3c3d44",
    bg_status_line_active = "#e0e0e2",
    fg_status_line_active = "#0a0a0a",
    bg_status_line_inactive = "#e8e8ea",
    fg_status_line_inactive = "#545458",
    bg_tab_bar = "#e0e0e2",
    bg_tab_current = "#f2f2f4",
    bg_tab_other = "#c8c8cc",
    fg_tab_other = "#2f2f33",
    bg_tab_alternate = "#d0d0e8",
    bg_added = "#c1f2d1",
    bg_added_faint = "#d8f8e1",
    bg_added_refine = "#aee5be",
    bg_added_fringe = "#6cc06c",
    fg_added = "#005000",
    fg_added_intense = "#006700",
    bg_changed = "#ffdfa9",
    bg_changed_faint = "#ffefbf",
    bg_changed_refine = "#fac090",
    bg_changed_fringe = "#d7c20a",
    fg_changed = "#553d00",
    fg_changed_intense = "#655000",
    bg_removed = "#ffd8d5",
    bg_removed_faint = "#ffe9e9",
    bg_removed_refine = "#f3b5af",
    bg_removed_fringe = "#d84a4f",
    fg_removed = "#8f1313",
    fg_removed_intense = "#aa2222",
    bg_diff_context = "#f8f8f8",
    string_fg = "#7f0000",
    -- string_fg = "#005000",
  },
  dark = {
    bg_main = "#000000",
    bg_dim = "#1e1e1e",
    bg_alt = "#0f0f0f",
    fg_main = "#ffffff",
    fg_dim = "#989898",
    fg_alt = "#c6daff",
    border = "#646464",
    border_highlight = "#C4C4C4",
    red = "#ff5f59",
    red_warmer = "#ff6b55",
    red_cooler = "#ff7f9f",
    red_faint = "#ff9580",
    green = "#44bc44",
    green_warmer = "#70b900",
    green_cooler = "#00c06f",
    green_faint = "#88ca9f",
    yellow = "#d0bc00",
    yellow_warmer = "#fec43f",
    yellow_cooler = "#dfaf7a",
    yellow_faint = "#d2b580",
    blue = "#2fafff",
    blue_warmer = "#79a8ff",
    blue_cooler = "#00bcff",
    blue_faint = "#82b0ec",
    magenta = "#feacd0",
    magenta_warmer = "#f78fe7",
    magenta_cooler = "#b6a0ff",
    magenta_faint = "#caa6df",
    cyan = "#00d3d0",
    cyan_warmer = "#4ae2f0",
    cyan_cooler = "#6ae4b9",
    cyan_faint = "#9ac8e0",
    rust = "#db7b5f",
    gold = "#c0965b",
    olive = "#9cbd6f",
    slate = "#76afbf",
    indigo = "#9099d9",
    maroon = "#cf7fa7",
    pink = "#d09dc0",
    red_intense = "#ff5f5f",
    green_intense = "#44df44",
    yellow_intense = "#efef00",
    blue_intense = "#338fff",
    magenta_intense = "#ff66ff",
    cyan_intense = "#00eff0",
    bg_red_intense = "#9d1f1f",
    bg_green_intense = "#2f822f",
    bg_yellow_intense = "#7a6100",
    bg_blue_intense = "#1640b0",
    bg_magenta_intense = "#7030af",
    bg_cyan_intense = "#2266ae",
    bg_red_subtle = "#620f2a",
    bg_green_subtle = "#00422a",
    bg_yellow_subtle = "#4a4000",
    bg_blue_subtle = "#242679",
    bg_magenta_subtle = "#552f5f",
    bg_cyan_subtle = "#004065",
    bg_red_nuanced = "#2c0614",
    bg_green_nuanced = "#001904",
    bg_yellow_nuanced = "#222000",
    bg_blue_nuanced = "#0f0e39",
    bg_magenta_nuanced = "#230631",
    bg_cyan_nuanced = "#041529",
    bg_completion = "#2f447f",
    bg_hl_line = "#2f3849",
    bg_paren_match = "#2f7f9f",
    bg_paren_expression = "#453040",
    bg_char_0 = "#0050af",
    bg_char_1 = "#7f1f7f",
    bg_char_2 = "#625a00",
    bg_active = "#303030",
    fg_active = "#f4f4f4",
    bg_inactive = "#282828",
    fg_inactive = "#bfc0c4",
    bg_status_line_active = "#505050",
    fg_status_line_active = "#f0f0f0",
    bg_status_line_inactive = "#2d2d2d",
    fg_status_line_inactive = "#969696",
    bg_tab_bar = "#313131",
    bg_tab_current = "#000000",
    bg_tab_other = "#545454",
    fg_tab_other = "#f7f7f7",
    bg_tab_alternate = "#545490",
    bg_added = "#00381f",
    bg_added_faint = "#002910",
    bg_added_refine = "#034f2f",
    bg_added_fringe = "#237f3f",
    fg_added = "#a0e0a0",
    fg_added_intense = "#80e080",
    bg_changed = "#363300",
    bg_changed_faint = "#2a1f00",
    bg_changed_refine = "#4a4a00",
    bg_changed_fringe = "#8a7a00",
    fg_changed = "#efef80",
    fg_changed_intense = "#c0b05f",
    bg_removed = "#4f1119",
    bg_removed_faint = "#380a0f",
    bg_removed_refine = "#781a1f",
    bg_removed_fringe = "#b81a1f",
    fg_removed = "#ffbfbf",
    fg_removed_intense = "#ff9095",
    bg_diff_context = "#1a1a1a",
    string_fg = "#88ca9f",
  },
  dark_tinted = {
    bg_main = "#0d0e1c",
    bg_dim = "#1d2235",
    bg_alt = "#0f0f0f",
    fg_main = "#ffffff",
    fg_dim = "#989898",
    fg_alt = "#c6daff",
    border = "#61647a",
    border_highlight = "#b290b0",
    red = "#ff5f59",
    red_warmer = "#ff6b55",
    red_cooler = "#ff7f9f",
    red_faint = "#ff9f80",
    green = "#44bc44",
    green_warmer = "#70b900",
    green_cooler = "#00c06f",
    green_faint = "#88ca9f",
    yellow = "#d0bc00",
    yellow_warmer = "#fec43f",
    yellow_cooler = "#dfaf7a",
    yellow_faint = "#d2b580",
    blue = "#2fafff",
    blue_warmer = "#79a8ff",
    blue_cooler = "#00bcff",
    blue_faint = "#82b0ec",
    magenta = "#feacd0",
    magenta_warmer = "#f78fe7",
    magenta_cooler = "#b6a0ff",
    magenta_faint = "#caa6df",
    cyan = "#00d3d0",
    cyan_warmer = "#4ae2f0",
    cyan_cooler = "#6ae4b9",
    cyan_faint = "#9ac8e0",
    rust = "#db7b5f",
    gold = "#c0965b",
    olive = "#9cbd6f",
    slate = "#76afbf",
    indigo = "#9099d9",
    maroon = "#cf7fa7",
    pink = "#d09dc0",
    red_intense = "#ff5f5f",
    green_intense = "#44df44",
    yellow_intense = "#efef00",
    blue_intense = "#338fff",
    magenta_intense = "#ff66ff",
    cyan_intense = "#00eff0",
    bg_red_intense = "#9d1f1f",
    bg_green_intense = "#2f822f",
    bg_yellow_intense = "#7a6100",
    bg_blue_intense = "#1640b0",
    bg_magenta_intense = "#7030af",
    bg_cyan_intense = "#2266ae",
    bg_red_subtle = "#620f2a",
    bg_green_subtle = "#00422a",
    bg_yellow_subtle = "#4a4000",
    bg_blue_subtle = "#242679",
    bg_magenta_subtle = "#552f5f",
    bg_cyan_subtle = "#004065",
    bg_red_nuanced = "#350f14",
    bg_green_nuanced = "#002718",
    bg_yellow_nuanced = "#2c1f00",
    bg_blue_nuanced = "#131c4d",
    bg_magenta_nuanced = "#2f133f",
    bg_cyan_nuanced = "#04253f",
    bg_completion = "#483d8a",
    bg_hl_line = "#303a6f",
    bg_paren_match = "#2f7f9f",
    bg_paren_expression = "#453040",
    bg_char_0 = "#0050af",
    bg_char_1 = "#7f1f7f",
    bg_char_2 = "#625a00",
    bg_active = "#4a4f69",
    fg_active = "#f4f4f4",
    bg_inactive = "#2b3045",
    fg_inactive = "#bfc0c4",
    bg_status_line_active = "#393F51",
    fg_status_line_active = "#f0f0f0",
    bg_status_line_inactive = "#292d48",
    fg_status_line_inactive = "#969696",
    bg_tab_bar = "#2c3045",
    bg_tab_current = "#0d0e1c",
    bg_tab_other = "#4a4f6a",
    fg_tab_other = "#f7f7f7",
    bg_tab_alternate = "#4a4f94",
    bg_added = "#003a2f",
    bg_added_faint = "#002922",
    bg_added_refine = "#035542",
    bg_added_fringe = "#23884f",
    fg_added = "#a0e0a0",
    fg_added_intense = "#80e080",
    bg_changed = "#363300",
    bg_changed_faint = "#2a1f00",
    bg_changed_refine = "#4a4a00",
    bg_changed_fringe = "#8f7a30",
    fg_changed = "#efef80",
    fg_changed_intense = "#c0b05f",
    bg_removed = "#4f1127",
    bg_removed_faint = "#380a19",
    bg_removed_refine = "#781a3a",
    bg_removed_fringe = "#b81a26",
    fg_removed = "#ffbfbf",
    fg_removed_intense = "#ff9095",
    bg_diff_context = "#1a1f30",
    string_fg = "#88ca9f",
  },
}

local function apply()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "modus"

  local variant = vim.g.modus_variant or "default"
  local is_light = vim.o.background == "light"
  local key
  if is_light then
    key = "light"
  elseif variant == "tinted" then
    key = "dark_tinted"
  else
    key = "dark"
  end
  local c = palettes[key]

  -- Derived semantic colors
  c.bg_sidebar = c.bg_dim
  c.fg_sidebar = c.fg_main
  c.cursor = key == "dark_tinted" and c.magenta_warmer or c.fg_main
  c.comment = key == "dark_tinted" and c.fg_dim or c.fg_dim
  c.git_add_bg = key == "light" and c.bg_added or c.bg_dim
  c.git_change_bg = key == "light" and c.bg_changed or c.bg_dim
  c.git_delete_bg = key == "light" and c.bg_removed or c.bg_dim
  c.linenr_bg = key == "dark" and c.bg_dim or c.bg_main
  c.error = c.red_cooler
  c.warning = c.yellow_cooler
  c.info = c.blue_cooler
  c.hint = c.cyan_faint
  c.ok = c.green_cooler
  c.success = c.fg_added
  c.visual = c.bg_magenta_intense
  c.accent_light = c.blue_faint
  c.accent = c.blue_warmer
  c.accent_darker = c.blue
  c.accent_dark = c.blue_intense

  local NONE = "NONE"
  local bg_main = c.bg_main

  local function hi(group, opts)
    if opts.style then
      if type(opts.style) == "table" then
        opts = vim.tbl_extend("force", opts, opts.style)
      end
      opts.style = nil
    end
    vim.api.nvim_set_hl(0, group, opts)
  end

  local function set_highlights(groups)
    for group, opts in pairs(groups) do
      hi(group, opts)
    end
  end

  -- Terminal colors
  vim.g.terminal_color_0 = c.bg_main
  vim.g.terminal_color_8 = c.border
  vim.g.terminal_color_7 = c.fg_main
  vim.g.terminal_color_15 = c.fg_dim
  vim.g.terminal_color_1 = c.red
  vim.g.terminal_color_9 = c.red_intense
  vim.g.terminal_color_2 = c.green
  vim.g.terminal_color_10 = c.green_intense
  vim.g.terminal_color_3 = c.yellow
  vim.g.terminal_color_11 = c.yellow_intense
  vim.g.terminal_color_4 = c.blue
  vim.g.terminal_color_12 = c.blue_intense
  vim.g.terminal_color_5 = c.fg_main
  vim.g.terminal_color_13 = c.magenta_intense
  vim.g.terminal_color_6 = c.cyan
  vim.g.terminal_color_14 = c.cyan_intense

  set_highlights({
    -- UI
    Normal                           = { fg = c.fg_main, bg = bg_main },
    NormalNC                         = { fg = c.fg_main, bg = bg_main },
    NormalSB                         = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    TerminalNormal                   = { bg = c.bg_dim },
    NormalFloat                      = { fg = c.fg_active, bg = bg_main },
    FloatBorder                      = { fg = c.border, bg = bg_main },
    FloatTitle                       = { fg = c.border_highlight, bg = bg_main },
    Folded                           = { fg = c.green_faint, bg = c.bg_dim },
    LineNr                           = { fg = c.border, bg = c.linenr_bg },
    LineNrAbove                      = { fg = c.fg_dim, bg = c.linenr_bg },
    LineNrBelow                      = { fg = c.fg_dim, bg = c.linenr_bg },
    CursorLineNr                     = { fg = c.fg_active, bg = c.linenr_bg, bold = true },
    SignColumn                       = { fg = c.fg_dim, bg = c.linenr_bg },
    CursorLine                       = { fg = NONE, bg = c.bg_hl_line },
    CursorColumn                     = { fg = NONE, bg = c.bg_hl_line },
    NonText                          = { fg = c.fg_dim },
    ErrorMsg                         = { fg = c.fg_main, bg = c.bg_red_intense },
    Conceal                          = { fg = c.yellow_faint },
    Cursor                           = { fg = c.bg_main, bg = c.cursor },
    lCursor                          = { link = "Cursor" },
    CursorIM                         = { link = "Cursor" },
    ColorColumn                      = { fg = c.fg_main, bg = c.bg_dim },
    FoldColumn                       = { fg = c.fg_inactive, bg = c.bg_inactive },
    Search                           = { fg = c.fg_main, bg = c.bg_green_intense },
    IncSearch                        = { fg = c.fg_main, bg = c.bg_yellow_intense },
    CurSearch                        = { link = "IncSearch" },
    Substitute                       = { fg = c.fg_main, bg = c.bg_red_intense },
    QuickFixLine                     = { fg = c.fg_main, bg = c.bg_hl_line },
    Pmenu                            = { fg = c.fg_active, bg = bg_main },
    PmenuSel                         = { bg = c.bg_completion },
    PmenuSbar                        = { fg = c.fg_active, bg = c.bg_dim },
    PmenuThumb                       = { bg = c.border },
    PmenuBorder                      = { link = "FloatBorder" },
    Menu                             = { link = "Pmenu" },
    Scrollbar                        = { link = "PmenuSbar" },
    Directory                        = { fg = c.blue },
    Title                            = { fg = c.fg_alt, bold = true },
    Visual                           = { bg = c.bg_hl_line },
    VisualNOS                        = { link = "Visual" },
    WildMenu                         = { fg = c.fg_main, bg = c.visual },
    Whitespace                       = { link = "NonText" },
    StatusLine                       = { fg = c.fg_status_line_active, bg = c.bg_status_line_active },
    StatusLineNC                     = { fg = c.fg_status_line_inactive, bg = c.bg_status_line_active },
    TabLine                          = { fg = c.border, bg = c.bg_tab_bar, underline = true, sp = c.bg_status_line_active },
    TabLineSel                       = { fg = c.fg_main, bg = c.bg_status_line_active, bold = true, underline = true, sp = c.bg_status_line_active },
    TabLineFill                      = { fg = c.border, bg = c.bg_tab_bar, underline = true, sp = c.bg_status_line_active },
    WinBar                           = { link = "TabLineSel" },
    WinBarNC                         = { link = "TabLine" },
    EndOfBuffer                      = { fg = c.fg_inactive },
    MatchParen                       = { fg = c.fg_main, bg = c.bg_paren_match },
    ModeMsg                          = { fg = c.fg_main },
    MsgArea                          = { fg = c.fg_main },
    MoreMsg                          = { fg = c.blue },
    VertSplit                        = { fg = c.border },
    WinSeparator                     = { fg = c.border, bold = true },
    DiffAdd                          = { fg = c.fg_added, bg = c.bg_added },
    DiffDelete                       = { fg = c.fg_removed, bg = c.bg_removed },
    DiffChange                       = { fg = c.fg_changed, bg = c.bg_changed },
    DiffText                         = { fg = c.fg_changed, bg = c.bg_changed },
    SpecialKey                       = { fg = c.fg_dim },
    SpellBad                         = { sp = c.error, undercurl = true },
    SpellCap                         = { sp = c.warning, undercurl = true },
    SpellLocal                       = { sp = c.info, undercurl = true },
    SpellRare                        = { sp = c.hint, undercurl = true },
    WarningMsg                       = { fg = c.warning },
    Question                         = { fg = c.blue },
    ScrollbarThumb                   = { fg = c.border },

    User1                            = { fg = c.red_warmer, bold = true },
    User2                            = { fg = c.blue_warmer, bold = true },
    User3                            = { fg = c.fg_main, bold = true },
    User5                            = { fg = c.blue_warmer, bg = c.bg_status_line_active, bold = true },
    User6                            = { fg = c.fg_main, bg = c.bg_status_line_active },
    User7                            = { fg = c.fg_main, bold = true },
    User8                            = { fg = c.fg_main, bg = c.bg_status_line_active, bold = false },
    User9                            = { fg = c.bg_main, bg = c.blue_warmer, bold = false },

    -- Syntax
    Comment                          = { fg = c.comment, italic = true },
    String                           = { fg = c.string_fg },
    Character                        = { fg = c.blue_warmer },
    Boolean                          = { fg = c.blue, bold = true },
    Statement                        = { fg = c.magenta_cooler },
    Conditional                      = { fg = c.magenta_cooler },
    Repeat                           = { fg = c.magenta_cooler },
    Label                            = { fg = c.cyan },
    Keyword                          = { fg = c.magenta_cooler, italic = true },
    Exception                        = { fg = c.magenta_cooler },
    StorageClass                     = { fg = c.magenta_cooler },
    Structure                        = { fg = c.magenta_cooler },
    Constant                         = { fg = c.rust },
    Function                         = { fg = c.cyan, bold = true },
    Identifier                       = { fg = c.blue_faint },
    PreProc                          = { fg = c.rust },
    Include                          = { fg = c.magenta_cooler },
    Define                           = { fg = c.red_cooler },
    Macro                            = { fg = c.blue_warmer },
    PreCondit                        = { fg = c.red_cooler },
    Todo                             = { fg = c.magenta, bold = true },
    Type                             = { fg = c.cyan_cooler },
    TypeDef                          = { fg = c.cyan_warmer },
    Number                           = { fg = c.blue_faint },
    Float                            = { link = "Number" },
    Operator                         = { fg = c.fg_main },
    Tag                              = { fg = c.magenta },
    Delimiter                        = { fg = c.fg_main },
    Special                          = { fg = c.cyan_faint, bold = true },
    SpecialChar                      = { link = "Special" },
    Underlined                       = { fg = c.fg_alt, underline = true },
    Error                            = { fg = c.fg_main, bg = c.bg_red_intense },

    -- Misc syntax
    qfLineNr                         = { fg = c.fg_dim },
    qfFileName                       = { fg = c.blue },

    htmlH1                           = { fg = c.blue, bold = true },
    htmlH2                           = { fg = c.yellow, bold = true },
    htmlH3                           = { fg = c.magenta_cooler, bold = true },
    htmlH4                           = { fg = c.green, bold = true },
    htmlH5                           = { fg = c.red, bold = true },
    htmlH6                           = { fg = c.cyan_warmer, bold = true },

    mkdCodeDelimiter                 = { bg = c.bg_alt, fg = c.fg_main },
    mkdCodeStart                     = { fg = c.cyan_cooler, bold = true },
    mkdCodeEnd                       = { fg = c.cyan_cooler, bold = true },

    markdownHeadingDelimiter         = { fg = c.rust, bold = true },
    markdownCode                     = { fg = c.cyan_cooler },
    markdownCodeBlock                = { fg = c.cyan_cooler },
    markdownLinkText                 = { fg = c.blue, underline = true },
    markdownH1                       = { link = "@markup.heading.1" },
    markdownH2                       = { link = "@markup.heading.2" },
    markdownH3                       = { link = "@markup.heading.3" },
    markdownH4                       = { link = "@markup.heading.4" },
    markdownH5                       = { link = "@markup.heading.5" },
    markdownH6                       = { link = "@markup.heading.6" },

    -- LSP
    LspCodeLens                      = { fg = c.comment },
    LspInlayHint                     = { bg = bg_main, fg = c.comment, italic = true },
    LspReferenceText                 = { bg = c.bg_blue_intense, fg = c.fg_main },
    LspReferenceRead                 = { bg = c.bg_blue_intense, fg = c.fg_main },
    LspReferenceWrite                = { bg = c.bg_blue_intense, fg = c.fg_main },
    LspSignatureActiveParameter      = { link = "Visual" },
    LspInfoBorder                    = { fg = c.border_highlight, bg = bg_main },

    -- Diagnostics
    DiagnosticError                  = { fg = c.error, bold = true },
    DiagnosticWarn                   = { fg = c.warning, bold = true },
    DiagnosticInfo                   = { fg = c.info, bold = true },
    DiagnosticHint                   = { fg = c.hint, bold = true },
    DiagnosticOk                     = { fg = c.ok, bold = true },
    DiagnosticUnnecessary            = { fg = c.fg_dim },

    DiagnosticSignError              = { fg = c.error, bold = true },
    DiagnosticSignWarn               = { fg = c.warning, bold = true },
    DiagnosticSignInfo               = { fg = c.info, bold = true },
    DiagnosticSignHint               = { fg = c.hint, bold = true },
    DiagnosticSignOk                 = { fg = c.ok, bold = true },

    DiagnosticVirtualTextError       = { fg = c.error, bold = true },
    DiagnosticVirtualTextWarn        = { fg = c.warning, bold = true },
    DiagnosticVirtualTextInfo        = { fg = c.info, bold = true },
    DiagnosticVirtualTextHint        = { fg = c.hint, bold = true },
    DiagnosticVirtualTextOk          = { fg = c.ok, bold = true },

    DiagnosticUnderlineError         = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn          = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo          = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint          = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineOk            = { undercurl = true, sp = c.ok },

    TreesitterContext                = { bg = bg_main },
    TreesitterContextSeparator       = { link = "WinSeparator" },
    TreesitterContextLineNumber      = { bg = bg_main },

    -- Treesitter
    ["@variable"]                    = {},
    ["@variable.builtin"]            = { link = "Conditional" },
    ["@variable.parameter"]          = { fg = c.cyan },
    ["@variable.parameter.builtin"]  = { fg = c.cyan_faint },
    ["@variable.member"]             = { link = "Identifier" },

    ["@constant"]                    = { link = "Constant" },
    ["@constant.builtin"]            = { link = "Special" },
    ["@constant.macro"]              = { link = "Define" },

    ["@module"]                      = { link = "Include" },
    ["@module.builtin"]              = { link = "Conditional" },
    ["@label"]                       = { link = "Label" },

    ["@string"]                      = { link = "String" },
    ["@string.documentation"]        = { fg = c.green_faint, italic = true },
    ["@string.regex"]                = { fg = c.green_cooler },
    ["@string.escape"]               = { fg = c.yellow_faint },
    ["@string.special"]              = { fg = c.red_faint },
    ["@string.special.symbol"]       = { link = "Identifier" },
    ["@string.special.path"]         = { fg = c.blue },
    ["@string.special.url"]          = { fg = c.cyan_cooler },

    ["@character"]                   = { link = "Character" },
    ["@character.special"]           = { link = "SpecialChar" },

    ["@boolean"]                     = { link = "Boolean" },
    ["@number"]                      = { link = "Number" },
    ["@number.float"]                = { link = "Float" },

    ["@type"]                        = { link = "Type" },
    ["@type.builtin"]                = { link = "Type" },
    ["@type.definition"]             = { link = "Typedef" },

    ["@attribute"]                   = { link = "PreProc" },
    ["@attribute.builtin"]           = { link = "PreProc" },
    ["@property"]                    = { link = "@field" },

    ["@function"]                    = { link = "Function" },
    ["@function.builtin"]            = { link = "Special" },
    ["@function.call"]               = { link = "Special" },
    ["@function.macro"]              = { link = "Macro" },

    ["@function.method"]             = { link = "Function" },
    ["@function.method.call"]        = { link = "@function.method" },

    ["@constructor"]                 = { fg = c.yellow_cooler },
    ["@operator"]                    = { link = "Operator" },

    ["@keyword"]                     = { link = "Keyword" },
    ["@keyword.coroutine"]           = { link = "@keyword" },
    ["@keyword.function"]            = { fg = c.blue_warmer },
    ["@keyword.operator"]            = { link = "@operator" },
    ["@keyword.import"]              = { link = "Include" },
    ["@keyword.type"]                = { link = "@type" },
    ["@keyword.modifier"]            = { link = "@keyword" },
    ["@keyword.repeat"]              = { link = "Repeat" },
    ["@keyword.return"]              = { link = "@keyword" },
    ["@keyword.debug"]               = { link = "Debug" },
    ["@keyword.exception"]           = { link = "Exception" },

    ["@keyword.conditional"]         = { link = "Conditional" },
    ["@keyword.conditional.ternary"] = { link = "Conditional" },

    ["@keyword.directive"]           = { link = "PreProc" },
    ["@keyword.directive.define"]    = { link = "Define" },

    ["@punctuation.delimiter"]       = { link = "Delimiter" },
    ["@punctuation.bracket"]         = { fg = c.fg_main },
    ["@punctuation.special"]         = { fg = c.fg_main },

    ["@comment"]                     = { link = "Comment" },
    ["@comment.documentation"]       = { link = "@string.documentation" },

    ["@comment.error"]               = { fg = c.error },
    ["@comment.warning"]             = { fg = c.warning },
    ["@comment.todo"]                = { link = "Todo" },
    ["@comment.note"]                = { fg = c.hint },

    ["@markup.strong"]               = { bold = true },
    ["@markup.italic"]               = { italic = true },
    ["@markup.strikethrough"]        = { strikethrough = true },
    ["@markup.underline"]            = { underline = true },

    ["@markup.heading"]              = { link = "Title" },
    ["@markup.heading.1"]            = { fg = c.blue, bold = true },
    ["@markup.heading.2"]            = { fg = c.yellow, bold = true },
    ["@markup.heading.3"]            = { fg = c.magenta_cooler, bold = true },
    ["@markup.heading.4"]            = { fg = c.green, bold = true },
    ["@markup.heading.5"]            = { fg = c.red, bold = true },
    ["@markup.heading.6"]            = { fg = c.cyan_warmer, bold = true },

    ["@markup.quote"]                = { italic = true },
    ["@markup.math"]                 = { link = "Special" },

    ["@markup.link"]                 = { fg = c.cyan_cooler },
    ["@markup.link.label"]           = { link = "SpecialChar" },
    ["@markup.link.label.symbol"]    = { link = "Identifier" },
    ["@markup.link.url"]             = { link = "Underlined" },

    ["@markup.raw"]                  = { link = "String" },
    ["@markup.raw.block"]            = { link = "String" },

    ["@markup.list"]                 = { fg = c.fg_main },
    ["@markup.list.checked"]         = { fg = c.green },
    ["@markup.list.unchecked"]       = { fg = c.yellow },

    ["@diff.plus"]                   = { link = "DiffAdd" },
    ["@diff.minus"]                  = { link = "DiffDelete" },
    ["@diff.delta"]                  = { link = "DiffChange" },

    ["@tag"]                         = { link = "Label" },
    ["@tag.attribute"]               = { link = "@property" },
    ["@tag.delimiter"]               = { link = "Delimiter" },

    ["@none"]                        = {},

    -- tsx
    ["@tag.tsx"]                     = { fg = c.red },
    ["@constructor.tsx"]             = { fg = c.blue },
    ["@tag.delimiter.tsx"]           = { fg = c.blue_cooler },

    -- diff
    diffAdded                        = { link = "DiffAdd" },
    diffRemoved                      = { link = "DiffDelete" },
    diffChanged                      = { link = "DiffChange" },
    diffOldFile                      = { fg = c.yellow },
    diffNewFile                      = { fg = c.yellow_warmer },
    diffFile                         = { fg = c.blue },
    diffLine                         = { fg = c.fg_alt },
    diffIndexLine                    = { fg = c.magenta },

    -- GitSigns
    GitSignsAdd                      = { fg = c.fg_added_intense, bg = c.git_add_bg },
    GitSignsChange                   = { fg = c.fg_changed_intense, bg = c.git_change_bg },
    GitSignsDelete                   = { fg = c.fg_removed_intense, bg = c.git_delete_bg },

    -- Fzf Lua
    FzfLuaNormal                     = { link = "Normal" },
    FzfLuaFzfNormal                  = { bg = c.bg_main },
    FzfLuaBorder                     = { fg = c.border, bg = bg_main },
    FzfLuaTitle                      = { fg = c.fg_dim, bg = bg_main },
    FzfLuaHeaderBind                 = { fg = c.gold },
    FzfLuaHeaderText                 = { fg = c.yellow_cooler },
    FzfLuaPathColNr                  = { fg = c.cyan_cooler },
    FzfLuaPathLineNr                 = { fg = c.green_cooler },
    FzfLuaBufName                    = { fg = c.magenta_warmer },
    FzfLuaBufNr                      = { fg = c.gold },
    FzfLuaBufFlagCur                 = { fg = c.yellow_cooler },
    FzfLuaBufFlagAlt                 = { fg = c.cyan_cooler },
    FzfLuaTabTitle                   = { fg = c.blue_warmer },
    FzfLuaTabMarker                  = { fg = c.gold },
    FzfLuaLiveSym                    = { fg = c.gold },
    FzfLuaFzfPointer                 = { link = "TerminalNormal" },
    FzfLuaLivePrompt                 = { fg = c.fg_main },
    FzfLuaBackDrop                   = { bg = c.bg_main },
    TitleFzf                         = { fg = c.bg_status_line_active, bg = c.bg_status_line_active },
    fzf1                             = { link = "StatusLine" },
    fzf2                             = { link = "StatusLine" },
    fzf3                             = { link = "StatusLine" },

    -- Telescope
    TelescopeBorder                  = { link = "FloatBorder" },

    BlinkCmpMenuBorder               = { link = "FloatBorder" },
    BlinkCmpSignatureHelpBorder      = { link = "FloatBorder" },
    BlinkCmpDocBorder                = { link = "FloatBorder" },
    BlinkCmpLabelMatch               = { fg = c.blue_warmer, bold = true },

    -- BlinkCmpKindStruct               = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindFunction             = { fg = c.blue, bg = c.bg_hl_line },
    -- BlinkCmpKindText                 = { fg = c.rust, bg = c.bg_hl_line },
    -- BlinkCmpKindClass                = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindValue                = { fg = c.rust, bg = c.bg_hl_line },
    -- BlinkCmpKindEnum                 = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindInterface            = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindMethod               = { fg = c.cyan, bg = c.bg_hl_line },
    -- BlinkCmpKindUnit                 = { fg = c.red, bg = c.bg_hl_line },
    -- BlinkCmpKindConstant             = { fg = c.fg_main, bg = c.bg_hl_line },
    -- BlinkCmpKindField                = { fg = c.blue, bg = c.bg_hl_line },
    -- BlinkCmpKindModule               = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindKeyword              = { fg = c.magenta, bg = c.bg_hl_line },
    -- BlinkCmpKindEnumMember           = { fg = c.fg_main, bg = c.bg_hl_line },
    -- BlinkCmpKindProperty             = { fg = c.blue, bg = c.bg_hl_line },
    -- BlinkCmpKindOperator             = { fg = c.rust, bg = c.bg_hl_line },
    -- BlinkCmpKindReference            = { fg = c.fg_main, bg = c.bg_hl_line },
    -- BlinkCmpKindSnippet              = { fg = c.fg_main, bg = c.bg_hl_line },
    -- BlinkCmpKindTypeParameter        = { fg = c.yellow, bg = c.bg_hl_line },
    -- BlinkCmpKindVariable             = { fg = c.fg_main, bg = c.bg_hl_line },

    -- headlines / render-markdown
    CodeBlock                        = { bg = c.bg_dim },
    Headline                         = { bg = c.bg_blue_nuanced },
    Headline1                        = { bg = c.bg_blue_nuanced },
    Headline2                        = { bg = c.bg_yellow_nuanced },
    Headline3                        = { bg = c.bg_magenta_nuanced },
    Headline4                        = { bg = c.bg_green_nuanced },
    Headline5                        = { bg = c.bg_red_nuanced },
    Headline6                        = { bg = c.bg_cyan_nuanced },
    RenderMarkdownCodeInline         = { link = "markdownCode" },
    RenderMarkdownCode               = { link = "markdownCodeBlock" },
    RenderMarkdownH1                 = { link = "@markup.heading.1" },
    RenderMarkdownH2                 = { link = "@markup.heading.2" },
    RenderMarkdownH3                 = { link = "@markup.heading.3" },
    RenderMarkdownH4                 = { link = "@markup.heading.4" },
    RenderMarkdownH5                 = { link = "@markup.heading.5" },
    RenderMarkdownH6                 = { link = "@markup.heading.6" },
    RenderMarkdownH1Bg               = { fg = c.blue, bg = c.bg_blue_nuanced },
    RenderMarkdownH2Bg               = { fg = c.yellow, bg = c.bg_yellow_nuanced },
    RenderMarkdownH3Bg               = { fg = c.magenta, bg = c.bg_magenta_nuanced },
    RenderMarkdownH4Bg               = { fg = c.green, bg = c.bg_green_nuanced },
    RenderMarkdownH5Bg               = { fg = c.red, bg = c.bg_red_nuanced },
    RenderMarkdownH6Bg               = { fg = c.cyan_warmer, bg = c.bg_cyan_nuanced },

    -- indent-blankline
    IndentBlanklineChar              = { fg = c.fg_dim, nocombine = true },
    IndentBlanklineContextChar       = { fg = c.magenta_cooler, nocombine = true },
    IblIndent                        = { fg = c.fg_dim, nocombine = true },
    IblScope                         = { fg = c.magenta_cooler, nocombine = true },

    -- NeoVim
    healthError                      = { fg = c.error },
    healthSuccess                    = { fg = c.green_cooler },
    healthWarning                    = { fg = c.warning },

    -- Yanky
    YankyPut                         = { link = "IncSearch" },
    YankyYanked                      = { link = "IncSearch" },

    -- Mini
    MiniCompletionActiveParameter    = { underline = true },
    MiniCursorword                   = { bg = c.fg_dim },
    MiniCursorwordCurrent            = { bg = c.fg_dim },
    MiniIndentscopeSymbol            = { link = "WinSeparator" },
    MiniIndentscopePrefix            = { nocombine = true },
    MiniJump                         = { bg = c.magenta_cooler, fg = c.fg_main },
    MiniJump2dSpot                   = { fg = c.magenta_cooler, bold = true, nocombine = true },
    MiniStarterCurrent               = { nocombine = true },
    MiniStarterFooter                = { fg = c.yellow, italic = true },
    MiniStarterHeader                = { fg = c.blue },
    MiniStarterInactive              = { fg = c.fg_dim },
    MiniStarterItem                  = { link = "Normal" },
    MiniStarterItemBullet            = { fg = c.border },
    MiniStarterItemPrefix            = { fg = c.yellow_cooler },
    MiniStarterSection               = { fg = c.blue_warmer },
    MiniStarterQuery                 = { fg = c.blue_cooler },
    MiniStatuslineDevinfo            = { fg = c.blue_faint, bg = c.bg_status_line_active, bold = true },
    MiniStatuslineFileinfo           = { fg = c.fg_status_line_active, bg = c.bg_status_line_active },
    MiniStatuslineFilename           = { fg = c.fg_status_line_active, bg = c.bg_status_line_active },
    MiniStatuslineInactive           = { fg = c.fg_status_line_inactive, bg = c.bg_status_line_inactive, bold = true },
    MiniStatuslineModeCommand        = { fg = c.bg_dim, bg = c.yellow_faint, bold = true },
    MiniStatuslineModeInsert         = { fg = c.bg_dim, bg = c.green_faint, bold = true },
    MiniStatuslineModeNormal         = { fg = c.bg_dim, bg = c.blue_faint, bold = true },
    MiniStatuslineModeOther          = { fg = c.bg_dim, bg = c.cyan_faint, bold = true },
    MiniStatuslineModeReplace        = { fg = c.bg_dim, bg = c.red_faint, bold = true },
    MiniStatuslineModeVisual         = { fg = c.bg_dim, bg = c.magenta_faint, bold = true },
    MiniSurround                     = { bg = c.yellow_warmer, fg = c.fg_main },
    MiniTablineCurrent               = { link = "TabLineSel" },
    MiniTablineFill                  = { link = "TabLineFill" },
    MiniTablineHidden                = { link = "TabLine" },
    MiniTablineModifiedCurrent       = { fg = c.yellow_cooler, bg = c.bg_status_line_active, bold = true },
    MiniTablineModifiedHidden        = { bg = c.bg_tab_other, fg = c.yellow_faint },
    MiniTablineModifiedVisible       = { fg = c.yellow_cooler, bg = c.bg_alt },
    MiniTablineTabpagesection        = { bg = c.bg_alt, fg = NONE },
    MiniTablineVisible               = { fg = c.fg_main, bg = c.bg_alt },
    MiniTestEmphasis                 = { bold = true },
    MiniTestFail                     = { fg = c.red, bold = true },
    MiniTestPass                     = { fg = c.green, bold = true },
    MiniTrailspace                   = { bg = c.red },

    -- mini.diff
    MiniDiffSignAdd                  = { fg = c.fg_added_intense, bg = bg_main },
    MiniDiffSignChange               = { fg = c.fg_changed_intense, bg = bg_main },
    MiniDiffSignDelete               = { fg = c.fg_removed_intense, bg = bg_main },
  })
end

-- Apply the theme
apply()

-- Re-apply when background changes (system light/dark mode toggle)
vim.api.nvim_create_autocmd("OptionSet", {
  pattern = "background",
  callback = function()
    if vim.g.colors_name == "modus" then
      apply()
    end
  end,
})
