local nvim_set_hl = vim.api.nvim_set_hl

if vim.g.colors_name then
  vim.cmd("hi clear")
end

vim.g.colors_name = "sora"
vim.o.termguicolors = true
vim.o.background = "dark"

local mod = require("utils").modify_colour

local variant = vim.g.sora_variant or "default"

local c = {
  bg                      = "#0e1018",
  bg_float                = "#0a0c12",
  bg_popup                = mod("#0a0c12", 200),
  bg_elevated             = "#14161e",
  -- bg_cursorline = "#171a24",
  bg_cursorline           = mod("#0e1018", 100),
  bg_selection            = mod("#0e1018", 100),
  bg_search               = "#1a3050",
  bg_statusline           = "#0a0c12",

  fg                      = "#c8d0e0",
  fg_dim                  = "#9aa4b8",
  fg_bright               = "#dce4f0",
  fg_comment              = "#586478",
  fg_gutter               = "#364050",
  fg_gutter_active        = "#6a7890",

  cyan                    = "#80c8e0",
  purple                  = "#b0a0d8",
  sage                    = "#90c8a0",
  rose                    = "#d0909c",
  gold                    = "#d4b878",
  peach                   = "#d0a888",
  teal                    = "#78b8b0",
  steel                   = "#8898b8",

  variable                = "#b4bcd0",
  accent                  = "#80c8e0",
  border                  = mod("#222838", 80),
  match_paren             = "#d4b878",
  guide                   = "#181c26",
  guide_active            = "#282e3c",
  nontext                 = "#222838",

  error                   = "#c46c78",
  warning                 = "#c8a860",
  info                    = "#5ca8c8",
  hint                    = "#78b0a0",
  ok                      = "#68a888",

  git_add                 = "#68b080",
  git_change              = "#6898b8",
  git_delete              = "#b86068",
  git_ignore              = "#586478",

  diff_add_fg             = "#74af68",
  diff_change_fg          = "#ffad29",
  diff_delete_fg          = "#ff4242",
  diff_text_fg            = "#34cae2",

  diff_add_bg             = "#1e2e24",
  diff_change_bg          = "#2d261a",
  diff_delete_bg          = "#2e1e20",
  diff_text_bg            = "#1c2b36",

  terminal_black          = "#0e1018",
  terminal_red            = "#c46c78",
  terminal_green          = "#90c8a0",
  terminal_yellow         = "#d4b878",
  terminal_blue           = "#80c8e0",
  terminal_magenta        = "#b0a0d8",
  terminal_cyan           = "#78b8b0",
  terminal_white          = "#c8d0e0",

  terminal_bright_black   = "#4a5468",
  terminal_bright_red     = "#d88898",
  terminal_bright_green   = "#a8d8b4",
  terminal_bright_yellow  = "#e0c888",
  terminal_bright_blue    = "#98d8f0",
  terminal_bright_magenta = "#c4b4e8",
  terminal_bright_cyan    = "#90d0c8",
  terminal_bright_white   = "#dce4f0",

  none                    = "NONE",
}

if variant == "dimmed" then
  c.bg = "#23283c"
  c.bg_float = mod("#212436", -20)
  c.bg_popup = mod("#23283c", 40)
  c.bg_elevated = "#2b2e42"
  c.bg_cursorline = "#2e3248"
  c.bg_selection = "#353c54"
  c.bg_search = "#314874"
  c.bg_statusline = mod("#212436", -20)
  c.border = mod("#23283c", 100)
  c.guide = "#2f344a"
  c.guide_active = "#3f4660"
  c.nontext = mod("#222838", 50)
  c.diff_add_bg = "#25343a"
  c.diff_change_bg = "#273040"
  c.diff_delete_bg = "#33182c"
  c.diff_text_bg = "#353c54"
  c.terminal_black = "#23283c"
  c.fg_gutter = mod("#364050", 40)
end

vim.g.terminal_color_0 = c.terminal_black
vim.g.terminal_color_1 = c.terminal_blue
vim.g.terminal_color_2 = c.terminal_green
vim.g.terminal_color_3 = c.terminal_yellow
vim.g.terminal_color_4 = c.terminal_blue
vim.g.terminal_color_5 = c.terminal_white
vim.g.terminal_color_6 = c.terminal_cyan
vim.g.terminal_color_7 = c.terminal_white
vim.g.terminal_color_8 = c.terminal_bright_black
vim.g.terminal_color_9 = c.terminal_blue
vim.g.terminal_color_10 = c.terminal_bright_green
vim.g.terminal_color_11 = c.terminal_bright_yellow
vim.g.terminal_color_12 = c.terminal_bright_blue
vim.g.terminal_color_13 = c.terminal_bright_magenta
vim.g.terminal_color_14 = c.terminal_bright_cyan
vim.g.terminal_color_15 = c.terminal_bright_white

local highlights = {
  Normal                                     = { fg = c.fg, bg = c.bg },
  NormalNC                                   = { fg = c.fg, bg = c.bg },
  TerminalNormal                             = { bg = c.bg_float },
  SidebarNormal                              = { bg = c.bg_float },
  DiffViewNormal                             = { link = "SidebarNormal" },
  DBUINormal                                 = { bg = c.bg_float },
  DBUIOutNormal                              = { bg = c.bg_float },
  NormalFloat                                = { fg = c.fg, bg = c.bg_float },
  FloatBorder                                = { fg = c.border, bg = c.bg },
  FloatTitle                                 = { fg = c.accent, bg = c.bg_float, bold = true },
  WinBar                                     = { fg = c.fg_dim, bg = c.none },
  WinBarNC                                   = { fg = c.fg_gutter, bg = c.none },

  Cursor                                     = { fg = c.bg, bg = c.fg },
  lCursor                                    = { link = "Cursor" },
  CursorIM                                   = { link = "Cursor" },
  TermCursor                                 = { fg = c.bg, bg = c.accent },
  TermCursorNC                               = { fg = c.bg, bg = c.fg_dim },
  CursorLine                                 = { bg = c.bg_cursorline },
  CursorColumn                               = { link = "CursorLine" },

  LineNr                                     = { fg = c.fg_gutter },
  CursorLineNr                               = { fg = c.accent, bg = c.bg_cursorline, bold = true },
  CursorLineFold                             = { fg = c.fg, bg = c.bg_cursorline, bold = true },
  CursorLineSign                             = { fg = c.accent, bg = c.bg_cursorline, bold = true },
  SignColumn                                 = { fg = c.fg_gutter, bg = c.none },
  FoldColumn                                 = { fg = c.fg_comment, bg = c.none },

  Search                                     = { fg = c.fg_bright, bg = c.bg_search },
  IncSearch                                  = { fg = c.bg, bg = c.accent },
  CurSearch                                  = { link = "IncSearch" },
  Substitute                                 = { fg = c.bg, bg = c.accent },

  Visual                                     = { bg = c.bg_selection },
  VisualNOS                                  = { link = "Visual" },
  VisualNonText                              = { fg = c.fg_comment, bg = c.bg_selection },

  StatusLine                                 = { fg = c.fg_dim, bg = c.bg_statusline },
  StatusLineNC                               = { fg = c.fg_gutter, bg = c.bg_statusline },
  WinSeparator                               = { fg = c.nontext },
  VertSplit                                  = { link = "WinSeparator" },

  TabLine                                    = { fg = c.fg_dim, bg = c.bg_float },
  TabLineFill                                = { bg = c.bg_float },
  TabLineSel                                 = { fg = c.fg_bright, bg = c.bg, bold = true },

  Pmenu                                      = { fg = c.fg, bg = c.bg_popup },
  PmenuSel                                   = { fg = c.fg_bright, bg = c.bg_selection },
  PmenuSbar                                  = { bg = c.bg_elevated },
  PmenuThumb                                 = { bg = c.fg_gutter },
  PmenuKind                                  = { fg = c.purple, bg = c.bg_popup },
  PmenuKindSel                               = { fg = c.purple, bg = c.bg_selection },
  PmenuExtra                                 = { fg = c.fg_dim, bg = c.bg_popup },
  PmenuExtraSel                              = { fg = c.fg_dim, bg = c.bg_selection },

  Folded                                     = { fg = c.fg_comment, bg = c.bg_cursorline },

  NonText                                    = { fg = c.fg_comment },
  SpecialKey                                 = { fg = c.nontext },
  Whitespace                                 = { fg = c.guide },
  EndOfBuffer                                = { fg = c.bg },
  MatchParen                                 = { fg = c.match_paren, bold = true },
  ModeMsg                                    = { fg = c.fg },
  MsgArea                                    = { fg = c.fg },
  MoreMsg                                    = { fg = c.cyan },
  Question                                   = { fg = c.cyan },
  Directory                                  = { fg = c.cyan },
  Title                                      = { fg = c.accent, bold = true },
  ErrorMsg                                   = { fg = c.error },
  WarningMsg                                 = { fg = c.warning },
  Conceal                                    = { fg = c.fg_dim },
  SpellBad                                   = { sp = c.error, undercurl = true },
  SpellCap                                   = { sp = c.warning, undercurl = true },
  SpellLocal                                 = { sp = c.info, undercurl = true },
  SpellRare                                  = { sp = c.hint, undercurl = true },
  ColorColumn                                = { bg = c.bg_cursorline },
  QuickFixLine                               = { bg = c.bg_selection, bold = true },
  WildMenu                                   = { link = "PmenuSel" },

  Comment                                    = { fg = c.fg_comment, italic = true },
  String                                     = { fg = c.sage },
  Character                                  = { fg = c.sage },
  Number                                     = { fg = c.gold },
  Float                                      = { link = "Number" },
  Boolean                                    = { fg = c.rose, italic = true },
  Identifier                                 = { fg = c.variable },
  Function                                   = { fg = c.cyan },
  Statement                                  = { fg = c.purple },
  Conditional                                = { fg = c.purple, italic = true },
  Repeat                                     = { fg = c.purple, italic = true },
  Label                                      = { fg = c.teal },
  Operator                                   = { fg = c.steel },
  Keyword                                    = { fg = c.purple, italic = true },
  Exception                                  = { fg = c.rose },
  PreProc                                    = { fg = c.purple },
  Include                                    = { fg = c.purple, italic = true },
  Define                                     = { fg = c.purple },
  Macro                                      = { fg = c.teal, bold = true },
  PreCondit                                  = { fg = c.purple },
  Type                                       = { fg = c.peach },
  StorageClass                               = { fg = c.purple, italic = true },
  Structure                                  = { fg = c.peach, bold = true },
  Typedef                                    = { fg = c.peach },
  Constant                                   = { fg = c.gold },
  Special                                    = { fg = c.teal },
  SpecialChar                                = { fg = c.teal },
  Tag                                        = { fg = c.teal },
  Delimiter                                  = { fg = c.fg_dim },
  SpecialComment                             = { fg = c.gold, italic = true },
  Debug                                      = { fg = c.rose },
  Underlined                                 = { fg = c.cyan, underline = true },
  Bold                                       = { bold = true },
  Italic                                     = { italic = true },
  Ignore                                     = { fg = c.nontext },
  Error                                      = { fg = c.error },
  Todo                                       = { fg = c.bg, bg = c.gold, bold = true },

  ["@variable"]                              = { fg = c.variable },
  ["@variable.builtin"]                      = { fg = c.rose, italic = true },
  ["@variable.parameter"]                    = { fg = c.peach },
  ["@variable.parameter.builtin"]            = { fg = c.peach, italic = true },
  ["@variable.member"]                       = { fg = c.steel },
  ["@constant"]                              = { fg = c.gold },
  ["@constant.builtin"]                      = { fg = c.gold, bold = true },
  ["@constant.macro"]                        = { fg = c.teal, bold = true },
  ["@module"]                                = { fg = c.fg_dim },
  ["@module.builtin"]                        = { fg = c.fg_dim, italic = true },
  ["@label"]                                 = { fg = c.teal },
  ["@string"]                                = { fg = c.sage },
  ["@string.documentation"]                  = { fg = c.sage, italic = true },
  ["@string.escape"]                         = { fg = c.teal, bold = true },
  ["@string.regexp"]                         = { fg = c.teal },
  ["@string.special"]                        = { fg = c.teal },
  ["@string.special.symbol"]                 = { fg = c.gold },
  ["@string.special.url"]                    = { fg = c.cyan, underline = true },
  ["@string.special.path"]                   = { fg = c.cyan },
  ["@character"]                             = { fg = c.sage },
  ["@character.special"]                     = { fg = c.teal },
  ["@number"]                                = { fg = c.gold },
  ["@number.float"]                          = { fg = c.gold },
  ["@boolean"]                               = { fg = c.rose, italic = true },
  ["@type"]                                  = { fg = c.peach },
  ["@type.builtin"]                          = { fg = c.peach, italic = true },
  ["@type.definition"]                       = { fg = c.peach, bold = true },
  ["@type.qualifier"]                        = { fg = c.purple, italic = true },
  ["@attribute"]                             = { fg = c.peach },
  ["@attribute.builtin"]                     = { fg = c.peach, italic = true },
  ["@function"]                              = { fg = c.cyan },
  ["@function.builtin"]                      = { fg = c.cyan, italic = true },
  ["@function.call"]                         = { fg = c.cyan },
  ["@function.macro"]                        = { fg = c.teal, bold = true },
  ["@function.method"]                       = { fg = c.cyan },
  ["@function.method.call"]                  = { fg = c.cyan },
  ["@constructor"]                           = { fg = c.peach, bold = true },
  ["@operator"]                              = { fg = c.steel },
  ["@keyword"]                               = { fg = c.purple, italic = true },
  ["@keyword.coroutine"]                     = { fg = c.purple, italic = true },
  ["@keyword.function"]                      = { fg = c.purple, italic = true },
  ["@keyword.operator"]                      = { fg = c.steel },
  ["@keyword.import"]                        = { fg = c.purple, italic = true },
  ["@keyword.type"]                          = { fg = c.purple },
  ["@keyword.modifier"]                      = { fg = c.purple, italic = true },
  ["@keyword.repeat"]                        = { fg = c.purple, italic = true },
  ["@keyword.return"]                        = { fg = c.purple, italic = true },
  ["@keyword.debug"]                         = { fg = c.rose },
  ["@keyword.exception"]                     = { fg = c.rose },
  ["@keyword.conditional"]                   = { fg = c.purple, italic = true },
  ["@keyword.conditional.ternary"]           = { fg = c.steel },
  ["@keyword.directive"]                     = { fg = c.cyan },
  ["@keyword.directive.define"]              = { fg = c.purple },
  ["@punctuation.bracket"]                   = { fg = c.fg_dim },
  ["@punctuation.delimiter"]                 = { fg = c.fg_dim },
  ["@punctuation.special"]                   = { fg = c.steel },
  ["@comment"]                               = { fg = c.fg_comment, italic = true },
  ["@comment.documentation"]                 = { fg = c.fg_comment, italic = true },
  ["@comment.error"]                         = { fg = c.error, bold = true },
  ["@comment.warning"]                       = { fg = c.warning, bold = true },
  ["@comment.todo"]                          = { fg = c.bg, bg = c.gold, bold = true },
  ["@comment.note"]                          = { fg = c.bg, bg = c.info, bold = true },
  ["@markup.strong"]                         = { fg = c.fg_bright, bold = true },
  ["@markup.italic"]                         = { fg = c.fg_bright, italic = true },
  ["@markup.strikethrough"]                  = { fg = c.fg_dim, strikethrough = true },
  ["@markup.underline"]                      = { underline = true },
  ["@markup.heading"]                        = { fg = c.cyan, bold = true },
  ["@markup.heading.1"]                      = { fg = c.cyan, bold = true },
  ["@markup.heading.2"]                      = { fg = c.gold, bold = true },
  ["@markup.heading.3"]                      = { fg = c.peach, bold = true },
  ["@markup.heading.4"]                      = { fg = c.sage, bold = true },
  ["@markup.heading.5"]                      = { fg = c.gold, bold = true },
  ["@markup.heading.6"]                      = { fg = c.rose, bold = true },
  ["@markup.quote"]                          = { fg = c.fg_dim, italic = true },
  ["@markup.math"]                           = { fg = c.gold },
  ["@markup.environment"]                    = { fg = c.purple },
  ["@markup.link"]                           = { fg = c.cyan, underline = true },
  ["@markup.link.label"]                     = { fg = c.cyan },
  ["@markup.link.url"]                       = { fg = c.cyan, underline = true },
  ["@markup.raw"]                            = { fg = c.sage },
  ["@markup.raw.block"]                      = { fg = c.fg },
  ["@markup.list"]                           = { fg = c.steel },
  ["@markup.list.checked"]                   = { fg = c.ok },
  ["@markup.list.unchecked"]                 = { fg = c.fg_dim },
  ["@tag"]                                   = { fg = c.teal },
  ["@tag.builtin"]                           = { fg = c.teal, italic = true },
  ["@tag.attribute"]                         = { fg = c.peach },
  ["@tag.delimiter"]                         = { fg = c.fg_dim },
  ["@diff.plus"]                             = { fg = c.git_add },
  ["@diff.minus"]                            = { fg = c.git_delete },
  ["@diff.delta"]                            = { fg = c.git_change },

  LspReferenceText                           = { bg = c.guide_active },
  LspReferenceRead                           = { bg = c.guide_active },
  LspReferenceWrite                          = { bg = c.guide_active, underline = true },
  LspCodeLens                                = { fg = c.fg_comment },
  LspCodeLensSeparator                       = { fg = c.fg_gutter },
  LspSignatureActiveParameter                = { fg = c.accent, bold = true },
  LspInlayHint                               = { fg = c.fg_gutter, bg = c.bg_elevated, italic = true },
  DiagnosticError                            = { fg = c.error },
  DiagnosticWarn                             = { fg = c.warning },
  DiagnosticInfo                             = { fg = c.info },
  DiagnosticHint                             = { fg = c.hint },
  DiagnosticOk                               = { fg = c.ok },
  DiagnosticSignError                        = { fg = c.error },
  DiagnosticSignWarn                         = { fg = c.warning },
  DiagnosticSignInfo                         = { fg = c.info },
  DiagnosticSignHint                         = { fg = c.hint },
  DiagnosticSignOk                           = { fg = c.ok },
  DiagnosticVirtualTextError                 = { fg = c.error, bg = c.bg_elevated },
  DiagnosticVirtualTextWarn                  = { fg = c.warning, bg = c.bg_elevated },
  DiagnosticVirtualTextInfo                  = { fg = c.info, bg = c.bg_elevated },
  DiagnosticVirtualTextHint                  = { fg = c.hint, bg = c.bg_elevated },
  DiagnosticVirtualTextOk                    = { fg = c.ok, bg = c.bg_elevated },
  DiagnosticUnderlineError                   = { sp = c.error, undercurl = true },
  DiagnosticUnderlineWarn                    = { sp = c.warning, undercurl = true },
  DiagnosticUnderlineInfo                    = { sp = c.info, undercurl = true },
  DiagnosticUnderlineHint                    = { sp = c.hint, undercurl = true },
  DiagnosticUnderlineOk                      = { sp = c.ok, undercurl = true },
  DiagnosticFloatingError                    = { fg = c.error },
  DiagnosticFloatingWarn                     = { fg = c.warning },
  DiagnosticFloatingInfo                     = { fg = c.info },
  DiagnosticFloatingHint                     = { fg = c.hint },
  DiagnosticFloatingOk                       = { fg = c.ok },
  ["@lsp.type.boolean"]                      = { link = "@boolean" },
  ["@lsp.type.builtinType"]                  = { link = "@type.builtin" },
  ["@lsp.type.comment"]                      = { link = "@comment" },
  ["@lsp.type.decorator"]                    = { link = "@attribute" },
  ["@lsp.type.deriveHelper"]                 = { link = "@attribute" },
  ["@lsp.type.enum"]                         = { link = "@type" },
  ["@lsp.type.enumMember"]                   = { link = "@constant" },
  ["@lsp.type.escapeSequence"]               = { link = "@string.escape" },
  ["@lsp.type.formatSpecifier"]              = { link = "@punctuation.special" },
  ["@lsp.type.function"]                     = { link = "@function" },
  ["@lsp.type.generic"]                      = { link = "@variable" },
  ["@lsp.type.interface"]                    = { fg = c.peach },
  ["@lsp.type.keyword"]                      = { link = "@keyword" },
  ["@lsp.type.lifetime"]                     = { link = "@keyword.modifier" },
  ["@lsp.type.macro"]                        = { link = "@function.macro" },
  ["@lsp.type.method"]                       = { link = "@function.method" },
  ["@lsp.type.namespace"]                    = { link = "@module" },
  ["@lsp.type.number"]                       = { link = "@number" },
  ["@lsp.type.operator"]                     = { link = "@operator" },
  ["@lsp.type.parameter"]                    = { link = "@variable.parameter" },
  ["@lsp.type.property"]                     = { link = "@variable.member" },
  ["@lsp.type.selfKeyword"]                  = { link = "@variable.builtin" },
  ["@lsp.type.selfTypeKeyword"]              = { link = "@variable.builtin" },
  ["@lsp.type.string"]                       = { link = "@string" },
  ["@lsp.type.struct"]                       = { link = "@type" },
  ["@lsp.type.type"]                         = { link = "@type" },
  ["@lsp.type.typeAlias"]                    = { link = "@type.definition" },
  ["@lsp.type.typeParameter"]                = { link = "@type" },
  ["@lsp.type.unresolvedReference"]          = { sp = c.error, undercurl = true },
  ["@lsp.type.variable"]                     = {},
  ["@lsp.typemod.class.defaultLibrary"]      = { link = "@type.builtin" },
  ["@lsp.typemod.enum.defaultLibrary"]       = { link = "@type.builtin" },
  ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
  ["@lsp.typemod.function.defaultLibrary"]   = { link = "@function.builtin" },
  ["@lsp.typemod.keyword.async"]             = { link = "@keyword.coroutine" },
  ["@lsp.typemod.keyword.injected"]          = { link = "@keyword" },
  ["@lsp.typemod.macro.defaultLibrary"]      = { link = "@function.builtin" },
  ["@lsp.typemod.method.defaultLibrary"]     = { link = "@function.builtin" },
  ["@lsp.typemod.operator.injected"]         = { link = "@operator" },
  ["@lsp.typemod.string.injected"]           = { link = "@string" },
  ["@lsp.typemod.struct.defaultLibrary"]     = { link = "@type.builtin" },
  ["@lsp.typemod.type.defaultLibrary"]       = { link = "@type.builtin" },
  ["@lsp.typemod.typeAlias.defaultLibrary"]  = { link = "@type.builtin" },
  ["@lsp.typemod.variable.callable"]         = { link = "@function" },
  ["@lsp.typemod.variable.defaultLibrary"]   = { link = "@variable.builtin" },
  ["@lsp.typemod.variable.injected"]         = { link = "@variable" },
  ["@lsp.typemod.variable.static"]           = { link = "@constant" },

  GitSignsAdd                                = { fg = c.git_add },
  GitSignsChange                             = { fg = c.git_change },
  GitSignsDelete                             = { fg = c.git_delete },
  GitSignsCurrentLineBlame                   = { fg = c.fg_comment },
  NeogitActiveItem                           = { bg = c.diff_text_bg },
  NeogitCommitViewHeader                     = { bg = c.bg_cursorline },
  NeogitGraphPurple                          = { fg = c.cyan },
  DiffAdd                                    = { bg = c.diff_add_bg },
  DiffChange                                 = { bg = c.diff_change_bg },
  DiffDelete                                 = { fg = c.diff_delete_bg, bg = c.diff_delete_bg },
  DiffText                                   = { bg = c.diff_text_bg },
  Added                                      = { fg = c.git_add },
  Changed                                    = { fg = c.git_change },
  Removed                                    = { fg = c.git_delete },

  User1                                      = { link = "DiagnosticError" },
  User5                                      = { fg = c.fg_dim, bold = true },
  User6                                      = { fg = c.fg_dim },
  User9                                      = { fg = c.sage },

  TreeSitterContext                          = { bg = c.bg, underline = true, sp = c.nontext },
  TreeSitterContextLineNumber                = { fg = c.fg, bg = c.bg, bold = true, underline = true, sp = c.nontext },

  SnacksPickerGitStatusUntracked             = { fg = c.fg_comment },
  SnacksPicker                               = { bg = c.bg_float },
  -- SnacksWinSeparator                         = { fg = c.bg_float, bg = c.bg_float },
  SnacksPickerInputBorder                    = { fg = c.border, bg = c.bg_float },
  SnacksPickerBorder                         = { fg = c.border, bg = c.bg_float },
  SnacksPickerInputTitle                     = { fg = c.blue, bg = c.bg_float },
  SnacksIndentScope                          = { fg = mod(c.fg_comment, -20) },
  SnacksIndent                               = { fg = mod(c.fg_comment, -50) },
  SnacksImageMath                            = { fg = c.cyan },

  MiniClueDescGroup                          = { bg = c.bg_popup },
  MiniClueDescSingle                         = { bg = c.bg_popup },
  MiniClueNextKey                            = { bg = c.bg_popup },
  MiniClueNextKeyWithPostkeys                = { bg = c.bg_popup },
  MiniClueSeparator                          = { fg = c.peach, bg = c.bg_popup },

  MiniFilesBorder                            = { fg = c.bg_float, bg = c.bg_float },

  BufferLineOffsetSeparator                  = { fg = c.nontext, bg = c.bg },
  BufferLineOffsetHelp                       = { fg = c.fg, bg = c.bg_dark },
  BufferLineOffset                           = { fg = c.fg, bg = c.bg_dark },
  BufferLineOffsetExplorer                   = { fg = c.fg, bg = c.bg_dark },
  BufferLineFill                             = { bg = c.bg_dark },
  BufferLineModified                         = { fg = mod(c.sage, -50), bg = "#0a0c12" },
  BufferLineModifiedVisible                  = { fg = mod(c.sage, -30), bg = "#0c0e16", },
  BufferLineModifiedSelected                 = { fg = c.sage, bg = c.bg },

  -- FzfLuaBackDrop                             = { bg = mod(c.bg, 0) },
  FzfLuaBorder                               = { fg = c.bg_float, bg = c.bg_float },
  FzfLuaFzfBorder                            = { fg = c.bg_float, bg = c.bg_float },
  FzfLuaPreviewBorder                        = { fg = c.bg_float, bg = c.bg_float },
  FzfLuaLivePrompt                           = { fg = c.fg },
  FzfLuaFzfHeader                            = { fg = c.blue },
  -- fzf1                                       = { link = "Statusline" },
  fzf1                                       = { fg = "bg", bg = "bg" },
  fzf2                                       = { link = "fzf1" },
  fzf3                                       = { link = "fzf1" },
  FzfLuaTitle                                = { link = "fzf1" },
  FzfLuaTitleFlags                           = { link = "fzf1" },
  FzfLuaFzfSeparator                         = { fg = c.bg },
  FzfLuaNormal                               = { link = "Normal" },

  RenderMarkdownH1Bg                         = { link = "DiagnosticVirtualTextInfo" },
  RenderMarkdownH2Bg                         = { link = "DiagnosticVirtualTextHint" },
  RenderMarkdownH3Bg                         = { link = "DiagnosticVirtualTextOk" },
  RenderMarkdownH4Bg                         = { link = "DiagnosticVirtualTextError" },
  RenderMarkdownH5Bg                         = { link = "DiagnosticVirtualTextWarn" },
  RenderMarkdownBullet                       = { fg = c.peach },

  Scrollbar                                  = { fg = c.nontext },
  ScrollbarThumb                             = { fg = c.fg_comment },

}

for group, opts in pairs(highlights) do
  nvim_set_hl(0, group, opts)
end
