alias pip="pip3"
alias jqt="QT_QPA_PLATFORM=wayland jupyter qtconsole"
alias ltmk="latexmk -interaction=nonstopmode -halt-on-error -pdf -output-directory=build"
alias l="ls -alh"
alias pypy="$HOME/tmp/pypy/pypy3.11-v7.3.20-linux64/bin/pypy"
alias open="xdg-open"
alias gst="git status"
alias gd="git diff"
alias ..="cd ../"
